### ISSUE TITLE
Custom Errormessage on $form->post()

### ISSUE THREAD

**Issue by ratiosoftware** [formr/Formr#1]
Seems custom error message (see below) is never displayed on

_$form->post('email','Email|Please enter your email address','valid_email');_

**$form->error_message()**

----
**Thank you for that helpfull tool !**

**Comment by timgavin** [comment]
To print out messages you should use `$form->messages()` :)

**Comment by timgavin** [comment]
I believe you should be using `$form->messages()` for your messaging.
