### ISSUE TITLE
request: option for input label creation

### ISSUE THREAD

**Issue by iamdevelish** [formr/Formr#10]
Hello,

could you include an option to whether create a label for the form inputs?

For my needs i did the following:

in class Formr add class global variable

public $generate_labels = false;

then change the class constructor to

function __construct($wrapper = '', $generate_labels = false) {
   $this->generate_labels = $generate_labels;
   ...
}

then in function label add this just before the closing bracket

        if ($this->generate_labels) {
            return $this->_create_label($data);
        }

**Comment by timgavin** [comment]
There are already a couple options to create labels for inputs.

```
$form->input_text('name', 'Name);

// creates
<label for="name">Name</label>
<input type="text" name="name">
```
Inputs
http://formr.github.io/methods/#inputtext

Labels
http://formr.github.io/methods/#labels
