### ISSUE TITLE
Dropdowns category+subcategory

### ISSUE THREAD

**Issue by xkpx64** [formr/Formr#100]
I just started to using dropdowns i read docs, but didn't find how to impelemnt subcategory tree in already made category.
![Capture](https://user-images.githubusercontent.com/5773378/112730447-485f1c80-8f3a-11eb-8f78-b06546d80974.PNG)
The original code

```
<div id="_books" class="form-group">
<label class="control-label" for="books">Books</label>
<select name="books" id="books" class="form-control">
			<option value="cat">The Cat in the Hat</option>
			<option value="lorax">The Lorax</option>
			<option value="yertle" selected>Yertle the Turtle</option>
			<option value="grinch">The Grinch Who Stole Christmas</option>
	</select>
</div>
```
To become something like this in picture
```
<div class="input-group mb-3">
<select class="custom-select" id="category" name="category" label="x">
	<optgroup label="Изберете клас" id="category" name="category">  
	<option value="5">5 клас</option><option value="6">6 клас</option><option value="7">7 клас</option><option value="8">8 клас</option>
	<option value="9">9 клас</option><option value="10">10 клас</option><option value="11">11 клас</option><option value="12">12 клас</option>
	</optgroup>
   </select>
<select class="custom-select" id="sub_category" name="sub_category">
	<optgroup label="Изберете Предмет" id="sub_category" name="sub_category">
	<option value="ФИЗИКА">ФИЗИКА</option> 
	<option value="БИОЛОГИЯ">БИОЛОГИЯ</option>
	<option value="МАТЕМАТИКА">МАТЕМАТИКА</option> 
	<option value="ИСТОРИЯ">ИСТОРИЯ</option>
	<option value="ХИМИЯ">ХИМИЯ</option> 
	<option value="АНГЛИЙСКИ">АНГЛИЙСКИ</option>
	<option value="ИНФОРМАТИКА">ИНФОРМАТИКА</option> 
	<option value="ТЕХНОЛОГИЙ">ТЕХНОЛОГИЙ</option>
	</optgroup>
  </select>
	<div class="input-group-append"> <button class="btn btn-success" type="submit">Качи</button> </div>		
</div>```

**Comment by timgavin** [comment]
I don't understand what you're asking, because what you did there was create two select menus, which is easy to do with Formr. If you're looking for custom functionality between the two menus then you're going to have to use javascript.

**Comment by xkpx64** [comment]
I must learn how to express myself better in english.
Well with formr creating [dropdown-select] its easy, but every ```form->select``` wraps the tag with ```<div class="input-group mb-3"> .<select-option1>.. </div>``` and can't insert <select-option2>to make subcategory like what i did in the picture.
This is produced by two select tags , is it possible to stack them like mine html on top
![Capture](https://user-images.githubusercontent.com/5773378/112743463-344e0600-8fa0-11eb-95fe-d69275bab854.PNG)

The idea/goal is 
div input-group mb-3
      select (category
      select (subcat)
  div-append  button  /div
/div

**Comment by timgavin** [comment]
This is not a Formr issue, but a layout issue. You need to build the form elements separately and place them in the HTML in the right locations.

```
<div class="row">
    <div class="col">
        <?php $form->select('select1'); ?>
    </div>
    <div class="col">
        <?php $form->select('select2'); ?>
    </div>
</div>
```
