### ISSUE TITLE
running project with formr on commandline throws Fatal Error

### ISSUE THREAD

**Issue by LPTT** [formr/Formr#101]
Hi,

if I run my cron scripts from command line I get:
`Fatal error: Trait 'Bootstrap' not found`

Although the cron itself does not need formr. The problem seems to be that composer autoload is loading class.formr.php which requires lib/class.formr.wrappers.php. 
Any ideas why this is happening on command line only?

**Comment by timgavin** [comment]
Please give me an example of your script so I can run it from the command prompt and test it out.

**Comment by LPTT** [comment]
it is enough if my testcron.php contains
`<?php
require_once __DIR__ . '/../vendor/autoload.php';
`

If I run
`php cron/testcron.php` it returns
`PHP Fatal error:  Trait 'Bootstrap' not found in /XYZ/vendor/formr/formr/lib/class.formr.wrappers.php on line 7`

However it works if run within the directory:
`cd cron
php testcron.php`

Tested with php7.3 and php7.4 on Linux and Mac.

**Comment by timgavin** [comment]
I've created a bare bones script with the include and an echo using php 7.4.15.

```
<?php
require_once __DIR__ . '/../vendor/autoload.php';
echo 'executed';
```

Running it from within the directory, and two times outside of the directory produce no errors.

```
php ~/Sites/test/formr/script.php
php formr/script.php
php script.php
```

I also added error reporting and it still executes with no errors.

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require_once __DIR__ . '/../vendor/autoload.php';
echo 'executed';
```

If you're including other libraries, have you checked for namespaces? Does anything you have conflict with the name `Bootstrap`?
