### ISSUE TITLE
save the last value in the cache of the forms - solved

### ISSUE THREAD

**Issue by lgremme** [formr/Formr#102]
After the submit of a form, I will get the cached value.

Test with hardcoded values (After submit back to the defaults):
```
<?php
echo 'My name is: ' . $_POST['name'] .' and I am: '. $_POST['age']. ' years old.';
?><html><body>
<form action="test.php" method="post">
 <p>Your name: <input type="text" name="name" value="Testname" /></p>
 <p>your age: <input type="text" name="age" value="1" /></p>
 <p><input type="submit" /></p>
</form>
</body>
</html>
```

Test with formr:
```
<?php
session_start();

require_once('Formr/class.formr.php');
$form = new Formr\Formr('bootstrap');
$form->open();
//$form->csrf();
echo "Last send: ". $_POST['agree'] . $_POST['Testname'] . $_POST['text1'];
$settings_testName = "Test_years";
$settings_test = 'years';

$form->checkbox('agree','I Agree','agree','agree','','','checked=""');
$form->checkbox($settings_testName,'Short Variable',$settings_test,$settings_testName,'','',$settings_test);
$form->text('text1','text2','text3','text4');
$form->submit_button('Submit Form');
$form->close();
?>
```
Result: With a unselected checkbox with submit the form, I will get a unchecked Checkbox. In this case must be the checkbox checked. I think, that are the values are cached. Later with the database I get very interesting results, e.g. Error in the SQL-Statement is very difficult to debug.

I think that the "agree"-checkbox will be checked in this case. The box is currently unchecked.

Test:
Change the value of the textbox and submit. You will get the changed values back.
The checkbox is the same thing.

Another idea is the caching in the system.

Thank you for your great work.

EDIT:
System details:
Ubuntu Raspberry Pi
PHP 7.4.3 (FPM) with lighttpd

**Comment by timgavin** [comment]
I'm sorry, I really don't understand what you're trying to tell me. Regardless, Formr doesn't cache anything.

You could be having trouble with your checkbox because you're trying to pass a string in the 7th parameter, instead of a boolean value.

This
```
$form->checkbox('agree','I Agree','agree','agree','','','checked=""');
```

Should be this
```
$form->checkbox('agree', 'I Agree', 'agree', 'agree', '', '', 'checked');
```

Or even this
```
$form->checkbox('agree', 'I Agree', 'agree', 'agree', '', '', true);
```

**Comment by lgremme** [comment]
Thank you for your reply.
```
<?php
session_start();

// Later in the code
require_once('Formr/class.formr.php');
$form = new Formr\Formr('bootstrap');
$form->open();
//$form->csrf();
echo "Last send: ". $_POST['agree'];

$form->checkbox('agree','I Agree','agree','agree','','','');
// Checkbox shouldn't selected after the submit.
$form->submit_button('Submit Form');
$form->close();
?>
```
I do the following steps:
1. select the agree checkbox and submit the form.
2. Result: Last send reply agree and the box is selected. 
The issue starts here: I think, I will get every time a unchecked checkbox back after the submit (default state). 

If I want to use the POST-Result from the submit, I have to do this one:
```
<?php
session_start();

// Later in the code
require_once('Formr/class.formr.php');
$form = new Formr\Formr('bootstrap');
$form->open();
//$form->csrf();
if (isset($_POST['agree'])) {
$checked = 'checked';
} else {
$checked = '';
}
echo "Last send: ". $_POST['agree'];

$form->checkbox('agree','I Agree','agree','agree','','',$checked);
// Result of POST-Variable
$form->submit_button('Submit Form');
$form->close();
?>
```
If I build a little mistake in the $checked at the checkbox in the form like $check, you will get after the selection of the checkbox a positive result, but it should be a unselected checkbox:

```
<?php
session_start();

// Later in the code
require_once('Formr/class.formr.php');
$form = new Formr\Formr('bootstrap');
$form->open();
//$form->csrf();
if (isset($_POST['agree'])) {
$checked = 'checked';
} else {
$checked = '';
}
echo "Last send: ". $_POST['agree'];

$form->checkbox('agree','I Agree','agree','agree','','',$check);
// Checkbox should be always unselected after the submit.
$form->submit_button('Submit Form');
$form->close();
?>
```

**Comment by timgavin** [comment]
Why are you manually checking if `agree` is checked, and then setting a `$checked` variable, and then using `$_POST['agree']`? Formr can do all of this for you automatically.

You're making your script more complicated than it needs to be.

Read the docs on `$post` and validation: https://formr.github.io/validation/

Copy and paste the following into a PHP script and you'll see the checkbox behave as expected. If it's checked and you submit the form, it'll stay checked. If you uncheck it and submit, it'll be unchecked.
```
if($form->submitted()) {
     $agree = $form->post('agree');

    // or you can do this
    if($form->post('agree')) {
        echo 'agree was checked';
     }
 }

$form->open();
$form->checkbox('agree', 'I Agree', 'agree', 'agree');
$form->submit_button();
$form->close();
```

**Comment by lgremme** [comment]
Thank you for your reply.

Your code looks in the first moment easy, but I'll publish the values to a sqlite3 database. If something went wrong, the database have the old values. In this case I'll stay unchecked, because the box in the database is checked.

How can I disable the feature to get the last state of POST-Variables?

**Comment by timgavin** [comment]
HTML checkboxes are boolean in nature: they're either checked [true] or unchecked [false].

Therefore the Formr checkbox receives a boolean value; `true` or `false`. So you need to make sure that whatever value is in your database is converted to a boolean for Formr. That's really all there is to it.

All you have to do is determine if your agree column in the database has a value or not. if it does, it's `true`, otherwise it's `false`.

```
$db_value = 1;

if($db_value) {
   $agree = true;
} else {
   $agree = false;
}

$form->checkbox('agree', 'I Agree', 'agree', 'agree', '', '', $agree);
```

**Comment by lgremme** [comment]
We found the issue in the code. We fixed the dynamic value of the third box with `true`. In our case the published value in the third parameter will be 0 and the checkbox is empty in all cases.
The third value must be always true.
```
[...]
$form->checkbox('value1','value2',true,$value4,'','',$checked);
[...]
```
