### ISSUE TITLE
not_matches for profile change password [old,new,confirm]

### ISSUE THREAD

**Issue by xkpx64** [formr/Formr#104]
Hey i am trying to do profile settings page to change user password. 
The idea is to have not_matches option that can check if old-pass is like new. How can i do it?
I want User to cannot change password to old password.

[old-pass] --> options --> min|max|etc..
[new-pass] --> options  --> matches[confirm_newpass], not_matches[old-pass]
[confirm-newpass] --> options --> same as newpass.

**Comment by timgavin** [comment]
You would have to check the new password against the old password in the database, which is outside the scope of Formr's capabilities.
