### ISSUE TITLE
Two submit_buttons error becouse same id

### ISSUE THREAD

**Issue by xkpx64** [formr/Formr#105]
I noticed error is thrown when i use two submit buttons becouse they are prebuild with same id(submit)
$form1->submit_button('Submit');
$form2->submit_button('Submit');
![Capture](https://user-images.githubusercontent.com/5773378/113513102-a3af9100-9570-11eb-8d1c-f22e51356993.PNG)

**Comment by timgavin** [comment]
https://formr.github.io/methods/#buttons

```
$form1->input_submit('submitOne', '', 'Submit One', 'submit-one');

$form2->input_submit('submitTwo', '', 'Submit Two', 'submit-two');
```
