### ISSUE TITLE
Bootstrap 5 Compatibility [question]

### ISSUE THREAD

**Issue by VincentCaruso** [formr/Formr#108]
Hello,

Is there any chance that you are making formr Bootstrap 5 compatible soon or are you waiting for the end of the beta period ?

(Close button is broken in form success message when using bootstrap 5, I can hack my way trough but I'd prefer the genuine library to take care of it).

Thanks for the beautiful library anyway, saved a couple of hours.

**Comment by timgavin** [comment]
I don't have any plans to implement it just yet; most likely waiting until it's official.

However, you can easily support 5 by creating a custom wrapper: https://github.com/formr/extend
