### ISSUE TITLE
Support for multi-page/step form?

### ISSUE THREAD

**Issue by kaanchan** [formr/Formr#110]
Hi,

I (quickly) looked through the Formr documentation and a Google search, but could not confirm if Formr supports multi-page/step forms.

I'd like to replace a legacy form that has 5 x front-end pages/files and 4 x field processing and submission files with a single .php file. But as the form is long, maintain that multi-page feel.

Is this possible with Formr?

**Comment by timgavin** [comment]
You can do multi-page forms by using a [`session`](https://formr.github.io/properties/#session) with Formr.

If you want to create a long form with a multi-page feel you'd probably want to put the form sections into divs and then use JavaScript to show/hide them as the user progresses.]

Perhaps hook the sectional submit buttons up to an Ajax call that stores the answers in a cookie or session, then read the contents of the cookie or session upon final submission. Or you could just use the sectional submit buttons to show/hide the divs. There's probably several ways to accomplish this, those are a couple off the top of my head.
