### ISSUE TITLE
Order of checks for Recapcha3

### ISSUE THREAD

**Issue by xkpx64** [formr/Formr#111]
I wanna ask is my order of checks right
```php
if ($form->submit()) { # executed
     if(!$form->errors()) {  # check if fields are okey
        if($form->recaptcha_passed()) { # then we check if user completed recapcha {
		... my code goes here
		} } } # closing 3 checks
```

**Comment by timgavin** [comment]
That will work.

However, if the reCAPTCHA fails the form dies, so it might make more sense to check for that first.

```php
if ($form->submitted())
{
    if ($form->recaptcha_passed())
    {
        // get our form values
        $name = $form->post('name');
        $email = $form->post('email');

        if ($form->ok())
        {
            // everything is good. send email, insert into db, etc...
        }
    }
}
```

You can also check if the reCAPTCHA failed and do something that way

```php
if ($form->submitted())
{
    if (! $form->recaptcha_passed())
    {
        // reCAPTCHA failed, define error message or do something else
        $form->error_message('Are you a bot?');
    }
}
```

**Comment by xkpx64** [comment]
Very interesting addition Thanks for the tips and your work Sir!

**Comment by xkpx64** [comment]
I see this code for RECaptcha in class.formr ```$return .= "   action: 'formr'\r\n";``` 
Isn't it suppose to be specific action name for every page that i include formr, so GAdminConsole  can differentiate which form is which and where is called.

Google says: [When you specify an action name in each place you execute reCAPTCHA, you enable the following new features ](https://developers.google.com/recaptcha/docs/v3#actions)
¤ A detailed break-down of data for your top ten actions in the admin console
¤ Adaptive risk analysis based on the context of the action, because abusive behavior can vary.
![Capture](https://user-images.githubusercontent.com/5773378/116667578-05fb8600-a9a5-11eb-8039-562ec99d626c.PNG)
### Fix for me was chaning recaptcha_body
```#$return .= "         action:'formr'\r\n";``` to ```$return .= "         action:'".$this->id."'\r\n";```
But this way i always need to specify ```$form->id = 'login';``` , no such a big deal

**Comment by timgavin** [comment]
This is a good catch and will be available in the next push. Though it might be better to check if an ID is available...

```php
if(! empty($this->id)) {
    $return .= "         action:'".$this->id."'\r\n";
} else {
    $return .= "         action:'Formr'\r\n";
}
```

**Comment by xkpx64** [comment]
Thanks Sir i'am learning alot from you and your class :)
