### ISSUE TITLE
Duplicate Labels on Checkboxes using a Array in the name attribute

### ISSUE THREAD

**Issue by shawn-crigger** [formr/Formr#112]
When using either checkbox or inline checkboxes, if the name has [] to make it an Array the label is displayed twice.

Below is some of the code I used to find the error, if you remove the [] from the name it works correctly, if you include it will display the label twice. 

You should be able to duplicate it with the below code just stick it in one of your examples.

```php
$name  = 'somethings[]';
$id        = '1';
$text     = 'Label';
$selected = false;

$field_data = array(
    'type' => 'checkbox',
    'name' => $name,
    'id' => 'something-'.$id,
    'value' => $id,
    'string' => null,
    'label' => $text,
    'selected' => $selected,
    'checkbox-inline' => 'inline'
);
echo $form->input_checkbox($field_data);

```

**Comment by timgavin** [comment]
What version are you using? I'm not seeing this in 1.3.3

Your code produces the following HTML

```html
<div id="_something-1" class="form-check form-check-inline">
    <input type="checkbox" name="somethings[]" id="something-1" value="1" class="form-check-input">
    <label for="something-1">Label</label>
</div>
```
