### ISSUE TITLE
_suppress_formr_validation_errors does not work on integer rule

### ISSUE THREAD

**Issue by LPTT** [formr/Formr#114]
`$form->custom_validation_messages = true;
$formr->post('sales, 'custom error message', 'integer');`
still appends "must be a number" on my custom error message.
I am on v1.3.3

**Comment by timgavin** [comment]
The custom error message goes after the field name and a pipe

```
$formr->post('sales, 'Sales|custom error message', 'integer');
```

https://formr.github.io/methods/#post
