### ISSUE TITLE
Checkbox showing as required in validation

### ISSUE THREAD

**Issue by LachieKimber** [formr/Formr#117]
Description of issue:
I have a form input as a inline checkbox and it is not required for the user to have it checked. I used custom javascript to prevent HTML5 Client from preventing me from submitting the form (which isn't ideal), but when it gets to the server side validation, I get the error message that the field is required. This is an issue as I have not set a validation rule for the input.

**Form Input:**
`$form->checkbox_inline('hire_marquee', "I'd like to hire a Marquee. $125 (inc GST). <em style='opacity:0.7; font-size: 0.8em;'>See FAQ for inclusions</em>",'hire_marquee','','data-required="false"','');`

**Server Side Validation:**
`$hire_marquee = $form->post('hire_marquee', 'Marquee');`

**Error Message:**
```
Please Correct the Following Error
Marquee is required
```

Please look into this! I will try my best to debug myself and post solution.

**Comment by timgavin** [comment]
Pretty sure you have a problem elsewhere as the code you're showing works without error. And FYI you can leave off any remaining parameters if they're not used.

```php
if($form->submitted()) {
    $hire_marquee = $form->post('hire_marquee', 'Marquee');
}

$form->open();
$form->checkbox_inline('hire_marquee', "I'd like to hire a Marquee. $125 (inc GST). <em style='opacity:0.7; font-size: 0.8em;'>See FAQ for inclusions</em>",'hire_marquee','','data-required="false"');
$form->submit_button();
$form->close();
```

Please show what you're using for `$form->required` if applicable. Otherwise you might want to check your javascript.

**Comment by LachieKimber** [comment]
Hi @timgavin,

My mistake! You were right, `$form-required` was setup wrong. I was using `$form->required = '*';`

Thanks! This is an awesome project.
