### ISSUE TITLE
Install error with Composer

### ISSUE THREAD

**Issue by celikbas** [formr/Formr#12]
When I tried to install with Composer I've got the following error:

`Could not find a version of package xlad/formr matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability. ` 

any suggestion?

**Comment by timgavin** [comment]
This repo isn't meant to be installed with Composer, and if it were it wouldn't be located at `xlad/formr` as that's a fork of this repo. This repo is `formr/Formr`.
