### ISSUE TITLE
XML or HTML4 feature

### ISSUE THREAD

**Issue by janstieler** [formr/Formr#122]
HI,
I'm ran actually in a little exotic problem. If I try to read the generated html from formr with php DOM as XML though `$dom->loadXML($html);` I get some errors with the selfclosing elements like an input.
```
DOMDocument::loadXML(): Opening and ending tag mismatch: input
```
It would be nice to add an xml/html4 feature for closing elements, or?
I'm actually not so familiar with your lib to say whats the best way to add this or how complex it is.

Cheers

**Comment by timgavin** [comment]
I can add this in the next release. For now you can easily update this by going to line 3007 in `class.formr.php` and changing this

```php
# insert the closing bracket
$return .= ' >';
```

to this

```php
# insert the closing bracket
$return .= ' />';
```

Edit: I believe you can avoid that error in the XML parser by using a more modern DOCTYPE, like HTML 5, where a closing tag is not required. Though I know that's not always an option.

Edit 2: The code above may not be the final solution, so make sure you check the release notes when 1.3.6 is pushed to avoid breaking your app.
