### ISSUE TITLE
Possibility to set class on parent element

### ISSUE THREAD

**Issue by janstieler** [formr/Formr#124]
Hi,
If you use Bootstrap or Bulma you have a construct for every input /Label with a parent element.
If someone try to build a formconstruct with a grid from the frameworks it is necessary to wrap again some div around the parent input/label element this will result in a mess of spaghetticode.
As an enhancement you could think about to st a parameter for the parent class. I think it will not make a different as there are exist five parameters yet and one more is not really a big messup :) .

Cheers

**Comment by timgavin** [comment]
Try using the [`hush`](https://formr.github.io/#1-create-the-form) parameter when instantiating Formr and see if it works for you. 

```php
$form = new Formr\Formr('bootstrap', 'hush');
```

I see that `hush` it not in the documentation, so I'll add it.

**Comment by timgavin** [comment]
Now that I think about it, hush probably isn't what you want. Are you looking to remove the enclosing div class, such as `form-group`?

Instead of this
```html
<div class="form-group">
    <input type="text" class="form-control">
</div>
```

You'd want this?
```html
<input type="text" class="form-control">
```

**Comment by timgavin** [comment]
You can now remove a framework's element wrapping div by adding 'nowrap' to the switch parameter when instantiating Formr.

```php
$form = new \Formr\Formr('bootstrap', 'nowrap');
```
