### ISSUE TITLE
preferred way to make forms for multiple database rows?

### ISSUE THREAD

**Issue by ipsod** [formr/Formr#125]
I need to make a form that's something like this:
[sku] [title] [price]
[sku] [title] [price]
[sku] [title] [price]
[sku] [title] [price]
[submit button]

Is there an idiomatic way to do this with Formr?

**Comment by timgavin** [comment]
Could you explain a little more about what you're trying to accomplish? Are you looking to build a form with database results? Or build an empty form with identical fields?

Regardless, it should be simple enough to just loop through an array and create/populate the fields with the data.

**Comment by ipsod** [comment]
Either/or - edit multiple or create multiple with identical fields.

Right now what I've got looks like this (just using some simple helper functions I wrote):

```php
<form action="" method="post">
    <? foreach ($products as $product) : ?>
        <?= img($product->get_thumbnail_uri()) ?>
        <div style='display: inline-block;'>
            <?= show_errors($errors, $product->sku) ?>
            <br />

            <?= hidden('sku[]', $product->sku); ?>

            <? $options = fks($categories, 'name') ?>
            <?= select('category_id[]', $options, $product->category_id, 'category_id') ?>

            <?= label('height[]', 'h'); ?>
            <?= number('height[]', $product->height, 5); ?>

            <?= label('diameter[]', 'd'); ?>
            <?= number('diameter[]', $product->diameter, 5); ?>

            <?= label('price[]', '$'); ?>
            <?= number('price[]', $product->price, 5); ?>
        </div>

        <br />
    <? endforeach; ?>
    <input type="submit" name="SubmitButton" value="submit" />
</form>

```

**Comment by timgavin** [comment]
It would probably be something kind of like this.

```php
require 'Formr/class.formr.php';
$form = new \Formr\Formr();

$form->messages();

$form->open();

foreach ($products as $product) {
    img($product->get_thumbnail_uri());
    $form->hidden('sku[]', $product->sku);
    $form->select('category_id[]', 'Category', $product->category_id, 'category_id', '', '', '', fks($categories, 'name'));
    $form->number('height[]', 'h', $product->height, 5);
    $form->number('diameter[]', 'd', $product->diameter, 5);
    $form->number('price[]', '$', $product->price, 5);
}

$form->button_submit();
$form->close();
```

**Comment by ipsod** [comment]
Thank you.  Is there any way to put the errors closer to the fields, or are the errors always all lumped at the top?

**Comment by timgavin** [comment]
> Thank you. Is there any way to put the errors closer to the fields, or are the errors always all lumped at the top?

Take a look at the 6th parameter for inputs: https://formr.github.io/methods/#text-inputs

If using Bootstrap or Bulma you can also specify if you want the field to show the appropriate field classes on success or error: https://formr.github.io/properties/#show_valid

**Comment by timgavin** [comment]
> Thank you. Is there any way to put the errors closer to the fields, or are the errors always all lumped at the top?

I've now added this into the wrappers (don't know why it took so long!) to make it easier. Instead of using the 6th parameter, you can just enable `$form->inline_errors` and the error messages will be injected into the wrapper and show under the field element.

```php
$form = new \Formr\Formr;
$form->inline_errors = TRUE;
```
