### ISSUE TITLE
Possible Bug with greater_than_or_equal/gte validation when number is 0

### ISSUE THREAD

**Issue by markusdittrich** [formr/Formr#128]
I was trying to validate that a number is greater than or equal to 0 and it didn't work. I took a look at the source code and found a possible bug:
```
if(! $match = $this->_get_matches($rule)) {
    return $data['post'];
}
```
This simply returns the post data if the return value of `_get_matches($rule)` is falsey, which it naturally is, if the return value is 0.

I rewrote this bit like this and it works as expected:
```
$match = $this->_get_matches($rule);
if($match === false) {
    return $data['post'];
}
```

Is this a bug or does it work as intended and I'm missing something? If it's a bug it surely also affects `gt[0]`, `lte[0]` and `lt[0]`, right?

**Comment by timgavin** [comment]
Good catch. Actually, it works just as well without the check

```php
$match = $this->_get_matches($rule);

if ((int)$data['post'] < (int)$match)
{
    if($this->_suppress_formr_validation_errors($data)) {
        $this->errors[$data['name']] = $data['string'];
    } else {
        $this->_validation_message($data, 'must be greater than, or equal to '.$match);
    }
}

return $data['post'];
```

Unfortunately everything but `0` will be returned to the form field after submit; a `0` will not show. Not sure where this is happening but I'll try to track it down.

I'll have this fixed in the next push.
