### ISSUE TITLE
greater_than_or_equal/gte Validation: Does it have to be Integers?

### ISSUE THREAD

**Issue by markusdittrich** [formr/Formr#129]
I'm trying to validate, that a number is greater than or equal to 0 and noticed that the comparison converts the numbers to Integers:
```
if ((int)$data['post'] < (int)$match)
{
   …
}
```
Unfortunately this results in -0.9 passing as greater than or equal to 0. Question: Would it cause any harm if I rewrote that part with `float` instead of `int`? Like so:
```
if ((float)$data['post'] < (float)$match)
{
   …
}
```

**Comment by timgavin** [comment]
I honestly don't know if it would cause an issue, so I don't want to mess around with that. Perhaps there's a way to add a `float` flag, to switch between int and float?...

**Comment by timgavin** [comment]
I've been playing around with this and actually don't see that I need to keep the casting in place. Removing (int) works just as well and allows you to check with negative floats. I mean, it's already checking to see if the value is numeric...

Are you seeing this behavior as well?

**Comment by markusdittrich** [comment]
Yes, simply removing it seems to work as well!

**Comment by timgavin** [comment]
This will be added in the next release

**Comment by timgavin** [comment]
1.4 has been released with the fixes.
