### ISSUE TITLE
Required indicator is not working with Bootstrap

### ISSUE THREAD

**Issue by vulantro** [formr/Formr#13]
Hello!

Require indicator is a useful features, but it only works when form instance is not created with Bootstrap. Once you set Bootstrap, everything looks fine, but there is no asterix after label names. I tried to fix it in wrappers.php, but no luck.
Could someone give some help?
Thank you.

**Comment by timgavin** [comment]
I think this was a major screwup on my end. I didn't plan this properly and never use a required indicator in my forms, so I didn't test it properly either. I'm working on a fix, but so far haven't been able to get it to work, so in the mean time you'll have to add them manually. Sorry.

**Comment by vulantro** [comment]
The problem seems to be in class.formr.wrappers.php in the following 2 lines:
181: this condition does not return true: $this->_check_required($data['name'])
182: this expression returns the default (empty) indicator: $this->required_indicator
if you set something in line 65 of class.formr.php and delete the condition mentioned above it puts a sign next to each input field (with no required check)

**Comment by timgavin** [comment]
Well, it's been a while since I worked with PHP outside of a framework, but I think what's happening is that `$form->required` is not being recognized because the wrapper is defined upon class instantiation.

Basically: `$form->required` isn't recognized in the wrapper because it's set _after_ the wrapper is set.

**Comment by vulantro** [comment]
I think `$this->required_indicator` is not overwritten as well. Could you please try fixing it? I tried switching some parts of the code but no success yet.
