### ISSUE TITLE
Possible Bug: required invalidates 0 in number field

### ISSUE THREAD

**Issue by markusdittrich** [formr/Formr#130]
I'm trying to validate a number input that is required and can be set to 0. Unfortunately such a field is marked as invalid if it is required since the corresponding if-condition only checks for `empty(0)` which returns true on `0`:

```
elseif ($rule == 'required' && empty($data['post']))
{
   …
}
```

Rewriting it like this with the use of the built-in `is_not_empty` method seems to work:
```
elseif ($rule == 'required' && $this->is_not_empty($data['post']) === false)
{
   …
}
```

Would this change break anything else?

**Comment by timgavin** [comment]
I don't think the change will cause any problems, as the `is_not_empty` function was specifically created to handle zeroes. See https://github.com/formr/Formr/issues/8 for more info.

However, looking at the original line, it's checking to see if the value is empty. In your change it's checking to see if the value is NOT empty. Is this intended? Did you mean to use the following (with added exclamation mark)?

```
elseif ($rule == 'required' && !$this->is_not_empty($data['post']) === false)
{
   …
}
```

**Comment by markusdittrich** [comment]
No, I think mines already fine. It checks if `is_not_empty` === `false`, making sure it's not _not_ empty.

**Comment by markusdittrich** [comment]
But surely `!is_not_empty` also works, but then you'd need to remove `=== false` at the end, as this would check if the value is not _not_ _not_ empty :D

**Comment by timgavin** [comment]
> But surely !is_not_empty also works, but then you'd need to remove === false at the end, as this would check if the value is not not not empty :D

Yeah, that's what I meant... and how it was designed lol

```php
elseif ($rule == 'required' && !$this->is_not_empty($data['post']))
```
