### ISSUE TITLE
I can't get the honeypot feature to work

### ISSUE THREAD

**Issue by ruifcastro** [formr/Formr#132]
Hi,

if I place $form->honeypot='password' in my code, nothing happens. But if I go into the library and place this public $honeypot=''password', it works. I get the the html code: '<input type="text" name="'.$this->honeypot.'" style="display:none">';

In the meanwhile, I have been using this $form->hidden('password') and then my own code to check the value.

I have no idea if it is something I'm doing wrong. If already check the library code, but I could identify any bug. But sadly, my known is limited.

I am using php 8.1.1

Not sure if this is the right place to ask for help.

**Comment by timgavin** [comment]
Please show your code.

**Comment by ruifcastro** [comment]
I'm using BladeOne templating library.

The view is something like this:
filename: formularioLayout.php
```
@php
	session_start();
	$form->form_open();
	$form->csrf(600);
	$form->required = 'username';
	$form->messages();
	$form->text('username','Number: ');
	$form->honeypot='password';
	$form->submit_button('Send');
	$form->form_close();
@endphp
```

$form->hidden('password'); I'm using this and not the honeypot above

Then in the php file that runs the above view and also checks the submit form the form:
```
use							eftec\bladeone\BladeOne;
include 						'eftec\BladeOne\lib\BladeOne.php';
use							Formr\Formr;
require_once					'Formr\class.formr.php';

function isLocalhost($whitelist = ['127.0.0.1', '::1', 'localhost']) {
    return in_array($_SERVER['REMOTE_ADDR'], $whitelist);
}

$form						= new Formr();
if (isLocalhost()) { //DEBUG
	$form->recaptcha_score		= 0.3;
	$form->recaptcha_site_key 	= '';
	$form->recaptcha_secret_key= '';
} else {
	$form->recaptcha_score		= 0.5;
	$form->recaptcha_site_key 	= '';
	$form->recaptcha_secret_key = '';
}

$sViews						= __DIR__ . '\views';
$sCompiles					= __DIR__ . '\compiles';
$blade						= new BladeOne($sViews,$sCompiles,BladeOne::MODE_DEBUG);

$sLang						= 'PT';
if ($_REQUEST['lang']==='en') {
	$sLang					= 'EN';
}

$iNAluno						='';
if($form->submitted()) {
	if(!$form->recaptcha_passed()) {
		$form				->error_message('An error has occurred. Please fill out the form again. (reCAPTCHA Failed)');
		echo $blade			->run('formularioLayout',['lang'=>$sLang,'form'=>$form]);
	} else {
		if ($form->post('password')==='') {
			$form			->sanitize_html = true;
			$iNAluno			=$form->validate('username(max[9]|int)');

			if ($form->ok()) {
				$form		->clear();
				$form		->success_message('Thank you!');
			} else {
				$iNAluno		='';
				$form		->add_to_errors('username|Por favor, insere um número de aluno válido!');
				echo $blade	->run('formularioLayout',['lang'=>$sLang,'form'=>$form]);
			}
		} else {
			//bot detection
			die;
		}
	}
} else {
	echo $blade				->run('formularioLayout',['lang'=>$sLang,'form'=>$form]);
}
```

My html is something like this with $form->hidden('password'). With $form->honeypot='password'; nothing appears:
```
<html>
<body>
<!--StartFragment-->

<form action="/ResetPassword/reset.php" id="formr" method="post" accept-charset="utf-8">
--
  | <input type="hidden" name="formrToken" id="formrToken" value="formrToken"><input type="hidden" name="csrf_token" value="62d8901a4d6ec85ec4307519384611d7cd735c2a9bc6bbdb94f7cc921efd5aa3\|1642014470">
  |  
  | <label for="username">Número: </label>
  | <input type="text" name="username" id="username" required />
  |  
  | <input type="hidden" name="password" id="password" value="">
  |  
  | <button type="submit" name="submit" id="submit" class="button">Enviar</button>
  |  
  |  
  | </form>

<!--EndFragment-->
</body>
</html>
```

**Comment by timgavin** [comment]
Try putting the honeypot code after your instantiate Formr if possible. Honeypot doesn't need to be inline with the form in the view because Formr will automatically put the honeypot field right after the `<form>` opening tag.

```php
$form = new Formr();
$form->honeypot='password';
```

**Comment by ruifcastro** [comment]
Yes it did work!

I thought it being part of the form, that it would make sense being between the form_open and form_close.

Sorry to bother you. I thought perhaps this was a bug.

Thank you.

**Comment by timgavin** [comment]
I can see why you would think that it should be with the form; I'll see if I can do something about making that less confusing. Glad it's working!

**Comment by timgavin** [comment]
I have added a new honeypot method to make this process more clear.

```php
$form->honeypot('password');
```

The old method will still work, so no need to update your code if you don't want to.

**Comment by ruifcastro** [comment]
Cool! Thx for the great work.
