### ISSUE TITLE
Recaptcha errors with file_get_contents()

### ISSUE THREAD

**Issue by ruifcastro** [formr/Formr#133]
Hi,

sometimes when the Recaptcha fails I get these errors below. I think it has to do with file_get_contents() function and certificate. This is a development server. So in a production server these warnings wouldn't appear, just a "Recaptcha failure" on my part.

I did find people talking about and suggesting to use curl https://stackoverflow.com/questions/33849880/recaptcha-file-get-contents-ssl-operation-failed
Here are some solutions https://www.titanwolf.org/Network/q/0b638b93-a5e4-4c5b-a51c-c705ef566584/y

I'm guessing since I'm doing it on a dev server using localhost, I get these errors. I hope in the production server this doesn't happen.

I'm just posting here because I don't know if this is something you should address. What do you think?

Errors:
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in vendor\Formr\class.formr.php on line 5130

Warning: file_get_contents(): Failed to enable crypto in vendor\Formr\class.formr.php on line 5130

Warning: file_get_contents(https://www.google.com/recaptcha/api/siteverify): Failed to open stream: operation failed in C:\inetpub\wwwroot\ResetPassword\vendor\Formr\class.formr.php on line 5130

Warning: Trying to access array offset on value of type null in vendor\Formr\class.formr.php on line 5135

My message:
Recaptcha failure

**Comment by timgavin** [comment]
I've tested both `file_get_contents()` and cURL locally and they're both working for me, so please give the code below a try and let me know if it works for you.

I've added a new parameter: `$recaptcha_use_curl` which will tell Formr you want to use cURL instead of `file_get_contents();`

On line 5130... Replace this

```php
$response = file_get_contents('https://www.google.com/recaptcha/api/siteverify', false, $context);
```

With this
```php
if ($this->recaptcha_use_curl) {
    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL => 'https://www.google.com/recaptcha/api/siteverify',
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => [
            'secret' => $this->recaptcha_secret_key,
            'response' => $_POST['formrToken'],
            'remoteip' => $_SERVER['REMOTE_ADDR']
        ],
        CURLOPT_RETURNTRANSFER => true
    ]);
    $response = curl_exec($ch);
    curl_close($ch);
} else {
    # file_get_contents() is the preferred way to read the contents of a file into a string
    $response = file_get_contents('https://www.google.com/recaptcha/api/siteverify', false, $context);
}
```

Add this around around line 110
```php
public $recaptcha_use_curl = false;
```

Then add this in your form code
```php
$form_recaptcha_use_curl = true;
```

Let me know how it goes!

**Comment by timgavin** [comment]
Went ahead and pushed it.

**Comment by ruifcastro** [comment]
Cool. Thx. I will test it out Monday.

**Comment by ruifcastro** [comment]
Good morning,

New error:
Warning: Trying to access array offset on value of type null in \vendor\Formr\class.formr.php on line 5152

I just placed this
```
session_start();
$form= new Formr();
$form->honeypot= 'password'; //botdetection
$form->recaptcha_use_curl= true;
```

I think the recaptacha got an error and since the variable $this->recaptcha_score was not initiate, I got the warning.

I usually got these recaptacha  errors when I leave the form page open and use it. But in this case with this new update, I'm getting it without timeout. I have to remove recaptcha_use_curl=true to work again

**Comment by ruifcastro** [comment]
testing the curl, If I add this, it works CURLOPT_SSL_VERIFYPEER => false.

```
curl_setopt_array($ch, [
CURLOPT_URL => 'https://www.google.com/recaptcha/api/siteverify',
CURLOPT_POST => true,
CURLOPT_POSTFIELDS => [
    'secret' => $this->recaptcha_secret_key,
    'response' => $_POST['formrToken'],
    'remoteip' => $_SERVER['REMOTE_ADDR']
],
CURLOPT_SSL_VERIFYPEER => false,
CURLOPT_RETURNTRANSFER => true
]);
```

The error I was getting is because $result was getting a false response. Perhaps you should also add a check if $result is empty, please check your connection or a Recaptch error?

This is my change and seems to work well
```
if (!empty($result) && $result['success'] == true && $result['score'] >= $this->recaptcha_score) {
   return true;
}
```

**Comment by timgavin** [comment]
Adding `CURLOPT_SSL_VERIFYPEER => false,` and testing if `$result` is not empty solves all the problems?

**Comment by ruifcastro** [comment]
Yes both, I get no errors.

When I read about the file_get_contents() problem, it was mostly about ssl connection. Curl has this option to ignore it and that's why it works.
