### ISSUE TITLE
PHP 8 Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by ruifcastro** [formr/Formr#141]
Hi,

just got this error. PHP 8 doesn't like variables being null in some cases.

Perhaps this should be looked at?
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in vendor\Formr\class.formr.php on line 2052

**Comment by timgavin** [comment]
Thanks, this will be fixed in the next push.
