### ISSUE TITLE
$form->post on array returns one element too much

### ISSUE THREAD

**Issue by chrilleferna** [formr/Formr#143]
I recently updated formr to version 1.4.2 (previous version I used had no version number) and encountered an annoying problem with form controls that are arrays (e.g; an array of check boxes). After submitting the form the PHP $_POST variable contains the correct elements, but the $form->post has an additional element with key=name and value = value of the last element.

An example: my form has an array of check boxes with the name set to "room_ids". Submitting such a form will return the following array in $_POST:
    [room_ids] => Array
        (
            [0] => 13751
            [1] => 85
            [2] => 86
            [3] => 87
        )

But $form-post('room_ids') is as follows:
    Array
    (
        [0] => 13751
        [1] => 85
        [2] => 86
        [3] => 87
        [room_ids] => 87
    )

This is a new behaviour and of course breaks my code in a large number of places

**Comment by chrilleferna** [comment]
Hi Tim, The problem comes from line 1846 in class.formr.php. I'm not sure I understand what your intention is with the section starting with the if on line 1838.... As a quick fix for me I have disabled that section, but this may have other impacts, maybe on fastform (which I don' use). Please advice

**Comment by timgavin** [comment]
Thanks!
