### ISSUE TITLE
Add a means to edit headers

### ISSUE THREAD

**Issue by ghost** [formr/Formr#146]
Could you look at a way to change mailheaders?

I my case I wanted to change the replyto header, but couldnt find it.

I'd love if you could either add something like a setHeaders method or a way to merge the replyto key with the to variable in the send_email method.

I hope I'm not being too vague. Otherwise Formr has worked great for me.

**Comment by timgavin** [comment]
No problem; I'll add that as the 6th parameter of the `send_email()` function.

**Comment by timgavin** [comment]
This has been added in v1.4.4
