### ISSUE TITLE
Getting each field error message

### ISSUE THREAD

**Issue by devbrainiac** [formr/Formr#147]
pls how can i get each field error message like its in the image
![Screenshot 2022-03-08 102625](https://user-images.githubusercontent.com/88845813/157302072-246b79bc-e7ce-49c1-8b7f-68b666e7a6f2.png)

**Comment by timgavin** [comment]
https://formr.github.io/properties/#inline_errors

**Comment by devbrainiac** [comment]
already check that but seem not understanding, pls can u just give me a sort of pieces code to echo the error in my form page like below code -> 

<?= form_error('name'); ?>
<?= form_error('password'); ?>
<?= form_error('agree'); ?>
