### ISSUE TITLE
getting field error 

### ISSUE THREAD

**Issue by devbrainiac** [formr/Formr#148]
already check that but seem not understanding, pls can u just give me a sort of pieces code to echo the error in my form page like below code -> 

> That's the code that you use. If it's not working for you, then please show your code.

**Comment by timgavin** [comment]
That's the code that you use. If it's not working for you, then please show your code.

**Comment by dahwaplord** [comment]
<<<?pho form_error('name'); ?>>>
<<<?= form_error('password'); ?>>>
<<<?= form_error('agree'); ?>>>

I need something like dis

**Comment by devbrainiac** [comment]
I need code like this screenshot 
![Screenshot_20220310-020857_Chrome](https://user-images.githubusercontent.com/88845813/157566975-5c1cf957-03dc-472d-9730-52bfe2e04272.jpg)

**Comment by timgavin** [comment]
Ok, I think I understand what you want. Add this function to `class.formr.php` and see if it's what you're looking for


```php
public function error($key)
{
    foreach ($this->errors as $k => $message) {
        if ($key == $k) {
            $this->_echo($message);
        }
    }
}
```

Then use it in your form like this

```php
$form->text('first_name', 'First name');
$form->error('first_name');

$form->text('last_name', 'Last name');
$form->error('last_name');
```

**Comment by devbrainiac** [comment]
Yeah u got me right 🙌, really appreciate and one more pls can unique validation be added, I mean to check data already exist in database field

**Comment by timgavin** [comment]
Cool, I'll add that to the next release.

Can you give me an example of what you mean by unique validation? Normally you'd just do `if($database->result == $somevariable)`, so I'm unclear how you'd use Formr to validate a database result, especially since Formr doesn't work with databases.

**Comment by devbrainiac** [comment]
This is sample class 

class UniqueRule extends Rule
{
    protected $message = ":attribute :value has been used";

    protected $fillableParams = ['table', 'column', 'except'];

    protected $pdo;

    public function __construct(PDO $pdo)
    {
        $this->pdo = $pdo;
    }

    public function check($value): bool
    {
        // make sure required parameters exists
        $this->requireParameters(['table', 'column']);

        // getting parameters
        $column = $this->parameter('column');
        $table = $this->parameter('table');
        $except = $this->parameter('except');

        if ($except AND $except == $value) {
            return true;
        }

        // do query
        $stmt = $this->pdo->prepare("select count(*) as count from `{$table}` where `{$column}` = :value");
        $stmt->bindParam(':value', $value);
        $stmt->execute();
        $data = $stmt->fetch(PDO::FETCH_ASSOC);

        // true for valid, false for invalid
        return intval($data['count']) === 0;
    }
}

And this is the usage 

$validation = $validator->validate($_POST, [
    'email' => 'email|unique:users,email'
]);

Check the library here 
https://github.com/rakit/validation
