### ISSUE TITLE
Can you specify type for input_button?

### ISSUE THREAD

**Issue by ghost** [formr/Formr#15]
Just wondering if there is a way I can specify the type field for the function input_button. Right now it defaults to type="button", but I want to be able to specify the button as type="submit". Ending result:

`<button type="submit" class="btn btn-primary btn-block">Apply Filters</button>`

Otherwise I would have to use jquery onclick command to submit the form. I prefer a button instead of a normal submit button because I dont need to specify a value for a button and it works differently in bootstrap for me with regards to styling in bootstrap 4.

**Comment by timgavin** [comment]
If I understood your question correctly, you want to use `input type="submit"` for your button?

Use `input_submit()` instead.

```
$form->input_submit('submit', '', 'Apply Filters', 'submit', 'class="btn-primary btn-block"');
```

Gives you

```
<input type="submit" name="submit" value="Apply Filters" id="submit" class="btn btn-primary btn-block">
```

**Comment by ghost** [comment]
> 
> 
> If I understood your question correctly, you want to use `input type="submit"` for your button?
> 
> Use `input_submit()` instead.
> 
> ```
> $form->input_submit('submit', '', 'Apply Filters', 'submit', 'class="btn-primary btn-block"');
> ```
> 
> Gives you
> 
> ```
> <input type="submit" name="submit" value="Apply Filters" id="submit" class="btn btn-primary btn-block">
> ```

As I said, I need type=submit for a button, I dont want to use input_submit. Sounds like your saying its not possible. Hopefully in the future if you make any changes please think about adding this option as it matters when using Bootstrap.

**Comment by timgavin** [comment]
it's possible, I just misunderstood. It's a perfectly reasonable request and I'll add it asap.

I don't want to break the existing `input_button()` function, so how does `input_button_submit()` sound?

Edit: I can update `input_button()` by adding a sixth `type` parameter, but that means if you want to use the defaults, you'll have to add 5 parameters before specifying the type, which seems like it would be overkill.

So it could be

```
$form->input_button('', '', '', '', '', 'submit');
```

or...

```
$form->input_button_submit();
```

**Comment by timgavin** [comment]
Here's an `input_button_submit()` function that should to the trick. If you want to use it right now you'll need to make a small change to the Formr class

Go to the `_button()` function (around line 2181) and update the following

### change this...

```
protected function _button($data)
{
    # build the button tag
    $return  = '<button type="button'; // <-- change this line
```

### ...to this

```
protected function _button($data)
{
    # build the button tag
    $return  = '<button type="'.$data['type'].'"'; // <-- to this line
```

Then just add the following new function under the `input_button()` function.

```
public function input_button_submit($data = '', $label = '', $value = '', $id = '', $string = '')
{
    if (!is_array($data)) {
        $data = array(
            'type' => 'submit',
            'name' => $data,
            'label' => $label,
            'value' => $value,
            'id' => $id,
            'string' => $string
        );
    } else {
        $data['type'] = 'submit';
    }

    return $this->_button($data);
}
```

I'll add this to Formr in the next update.

**Comment by ghost** [comment]
> 
> 
> Here's an `input_button_submit()` function that should to the trick. If you want to use it right now you'll need to make a small change to the Formr class
> 
> Go to the `_button()` function (around line 2181) and update the following
> ### change this...
> 
> ```
> protected function _button($data)
> {
>     # build the button tag
>     $return  = '<button type="button'; // <-- change this line
> ```
> 
> ### ...to this
> 
> ```
> protected function _button($data)
> {
>     # build the button tag
>     $return  = '<button type="'.$data['type'].'"'; // <-- to this line
> ```
> 
> Then just add the following new function under the `input_button()` function.
> 
> ```
> public function input_button_submit($data = '', $label = '', $value = '', $id = '', $string = '')
> {
>     if (!is_array($data)) {
>         $data = array(
>             'type' => 'submit',
>             'name' => $data,
>             'label' => $label,
>             'value' => $value,
>             'id' => $id,
>             'string' => $string
>         );
>     } else {
>         $data['type'] = 'submit';
>     }
> 
>     return $this->_button($data);
> }
> ```
> 
> I'll add this to Formr in the next update.

Thank you for adding this to your script! I just added the code per your instructions and as expected, works like a charm. Thanks again! Really love Formr. Best one that I have used and I have tried a lot of different ones. Just so easy! Thanks again!

**Comment by timgavin** [comment]
This has been included in the update I just posted.
