### ISSUE TITLE
FastForm with hush option

### ISSUE THREAD

**Issue by AndiLeni** [formr/Formr#151]
Hello,

I tried creating a form using FastForm, but since I use a templating system I need to save the form in a variable which I can pass to the template and echo later.

Unfortunately, I was not able to find an example how to do this.
I tried this, which does not work because the FastForm object can not be converted into a string.
```php
$form = new Formr\Formr('bootstrap', 'hush');
$form->fastform($database['form']);
echo $form;
```

Is this possible at all?

**Comment by AndiLeni** [comment]
I figured it out. While I was looking for a function like "echo" or similar, it is as simple as assigning directy from the `fastform` function.

```php
$form = new Formr\Formr('bootstrap', 'hush');
$form = $form->fastform($database['form']);
echo $form;
```

**Comment by timgavin** [comment]
You don't even need to do that, just echo the FastForm directly :)

```php
echo $form->fastform($database['form']);
```
