### ISSUE TITLE
POST after form submit contains "submit" entry

### ISSUE THREAD

**Issue by AndiLeni** [formr/Formr#152]
Hello,

I noticed, that the post data after form submits contains a "submit" value.
This is probably due to the fact, that the submit buttons have an `id` and a `name` attribute.
Is it possible to omit this value?

```
'name' => 'b'
'beschreibung' => 'artikel b'
'preis' => '12'
'submit' => 'Submit'
````

**Comment by timgavin** [comment]
No, but I'll omit it in the next update

**Comment by timgavin** [comment]
What are you using to get the POST values?

**Comment by AndiLeni** [comment]
I am using the $post = $form->fastpost('POST'); method. 
But instead of the 'POST' part as written in the docu I am using a native function of the surrounding web framework to access the post variables.

**Comment by timgavin** [comment]
`fastpost()` doesn't print the submit button, so whatever you're using seems to be bypassing `fastpost()`

The form
```php
$form->fastform('login');
```

After submission
```php
if ($form->submitted()) {
   $post = $form->fastpost('POST');
   $form->printr($post);
}
```

produces the following array

```
Array
(
    [FormrID] => login
    [username] => 
    [password] => 
)
```

**Comment by AndiLeni** [comment]
The problem was indeed not using `POST`. 
The submit value is not present anymore now.
Thanks for pointing to the right direction!
