### ISSUE TITLE
Pass data to fastform for editing

### ISSUE THREAD

**Issue by AndiLeni** [formr/Formr#153]
Hello,

how can I pass data to a form created with FastForm?
F.e. for editing existing entries, I want to pass data from the database to the form to edit these values.

**Comment by timgavin** [comment]
https://formr.github.io/fastform/

Pass an array to FastForm using your database results as the values.

**Comment by AndiLeni** [comment]
I beg your pardon, but I still struggle to figure out how to do this. 

I have f.e. set this variable as a global static form variable, to reuse it when necessary. 

```
$array = [
    'text' => 'name,Name,John Wick',
    'email' => 'email,Email,johnwick@gunfu.com',
    'textarea' => 'comments,Comments'
];
$form->fastform($array);
```

 I assume you intend me to create the "`name,Name,John Wick`" part manually and assign it to a new array?

**Comment by timgavin** [comment]
Something like this

```
$array = [
    'text' => 'name, Name,' . $databaseResult->name,
    'email' => 'email,Email,'.$databaseResult->email,
];

$form->fastform($array);
```
