### ISSUE TITLE
upload rename

### ISSUE THREAD

**Issue by mihajlo-zombori** [formr/Formr#154]
In file class.formr.php there is a problem with function _rename_file($handle)

with line:
```
# strip everything which surrounds our new filename
$string = trim($this->upload_rename, 'string[]');
```
it strips filename that starts/ends with every character defined here.
for example "glos" will becomes "lo".
Consider using preg_replace() instead

**Comment by timgavin** [comment]
Can you please give me an example of your code? I can not replicate this issue.

Edit: Never mind, I've been able to replicate it. This will be fixed in the next update. Thanks!
