### ISSUE TITLE
Regex rule confusing

### ISSUE THREAD

**Issue by AEimre** [formr/Formr#155]
The **regex** and **not_regex** validation rules work in the opposite way from how they should, imo. Currently, **regex** raises an error if the input _matches_ the rule, and **not_regex** raises an error when the input _doesn't match_ the rule. They should instead accept the input in both cases.

Every other rule works in the opposite (and intuitive) way, where the rule must be fulfilled, or otherwise an error is raised.

If you agree, the easiest fix is probably to switch `preg_match` and `!preg_match` in the two rules (lines [1988](https://github.com/formr/Formr/blob/master/class.formr.php#L1988) & [2002](https://github.com/formr/Formr/blob/master/class.formr.php#L2002)).

**Comment by timgavin** [comment]
The current rules are correct; the `not_regex` rule is designed to *not* match the given regular expression.

**Comment by AEimre** [comment]
Of course, that's the intention, but what I'm saying is that both rules work the opposite way of how they should.

Example:

`regex[/^foo$/]` will raise a validation error for input `foo`. But the rule should instead **accept** that value. It even says so in the comment:
```
# this rule must match a user-defined regex
if (mb_substr($rule, 0, 5) == 'regex')
{
    $rule = ltrim($rule, 'regex[');
    $rule = rtrim($rule, ']');
    
    if (preg_match($rule, $data['post']))
    {
        $this->_validation_message($data, 'does not match the required parameters');
    }
    
    return $data['post'];
}
```


And in the same manner, `not_regex[/^foo$/]` will accept the input `foo`, while it should actually **reject** it.
