### ISSUE TITLE
custom_validation_messages not working

### ISSUE THREAD

**Issue by loveGhb** [formr/Formr#156]
**Greetings, thanks for such a community class with checks and field customization!**

It seems to me that I found an error, **custom_validation_messages = true** does not work for me, messages of two types are immediately shown.

**Comment by timgavin** [comment]
Please give me an example of your code; I can not replicate this.

Also, make sure you are putting `$form->custom_validation_messages = true;` **before** you check if the form has been submitted.

```php
$form = new Formr\Formr();
$form->custom_validation_messages = true;

if ($form->submitted()) {
    $post = $form->post('name', 'Name|Custom Message', 'min[5]');
}
```
