### ISSUE TITLE
Honeypot

### ISSUE THREAD

**Issue by ruifcastro** [formr/Formr#158]
Hi,

I noticed that in the function honeypot the return string has a value=""

 ```
public function honeypot($name)
    {
        if ($this->honeypot) {
            $this->_error_message("Sorry! You can only have one Honeypot per form.<br>Please consider removing \$form->honeypot=\"" . $this->honeypot . "\"</code> from your code.");
        }
        
        $this->honeypot = $name;
        
        return $this->_echo('<input type="text" name="' . $name . '" value="" style="display:none">');
    }
```

But in the function _form($data) there is no value=""
```
# add the honeypot
        if($this->honeypot) {
            $return .= '<input type="text" name="' . $this->honeypot . '" style="display:none">';
        }
```

**Comment by timgavin** [comment]
`honeypot()` is a function you can place in your forms where you like. Use that when building your forms manually.

`$this->honeypot` is a "global" variable that's set when instantiating Formr. Use that when having Formr build forms for you.

```php
$form = new Formr;
$this->honeypot = 'myValue';
```

**Comment by ruifcastro** [comment]
Yes I know. But the function one places the html value="" and the global variable doesn't have a value=""

I think this one should be like this:

```
# add the honeypot
        if($this->honeypot) {
            $return .= '<input type="text" name="' . $this->honeypot . '" value="" style="display:none">';
        }
```

Shouldn't both have the same html output?

**Comment by timgavin** [comment]
Ok, I understand what you're saying. I don't believe the `value` attribute is actually necessary for the element, but I've added it anyway and will put it in the next update. Thanks.
