### ISSUE TITLE
info: How to limit choices on checkbox list

### ISSUE THREAD

**Issue by mdmiko** [formr/Formr#160]
Hi,
i need to add a checkboxlist on a form with 10 choices. It's possible to limit max choices to 3?
How i can do it? Thanks

**Comment by timgavin** [comment]
If you're limiting choices when the user is ticking checkboxes then you'll have to do this with javascript. If it's on the server side in PHP then you could just count how many were selected in the `$_POST` array and only allow 3. The is basically our of the scope of Formr.
