### ISSUE TITLE
formrToken value output in sent emails

### ISSUE THREAD

**Issue by dleetinc** [formr/Formr#162]
One of the best form processor libraries available. Thank you.

Questions: 

1. The sent email includes the CSRF token. What is the method to specify which form values are displayed on the printed emails?
2. Is there a plan to enable SMTP email sends or transactional email services within Formr?

Thank you.

**Comment by timgavin** [comment]
Thanks for the kind words :)

1. Please show me a code example of how you're sending email.

2. I don't plan on implementing any additional email services within Formr, as there are plenty of really good libraries out there that will do it much better than I can.

**Comment by timgavin** [comment]
Never mind, I got it. Will be fixed in the next release.
