### ISSUE TITLE
php 8.2 compatiblity

### ISSUE THREAD

**Issue by mihajlo-zombori** [formr/Formr#164]
There are many deprecation messages, this is just one of them:

Deprecated: Creation of dynamic property ::$required_fields is deprecated in class.formr.php on line 1341

**Comment by timgavin** [comment]
Thanks.

I can't replicate this. Can you show me what code you were using to get this error? And possibly any other errors?

**Edit**: see if this fixes it: 

Change this (line 1341)
```php
$this->required_fields = array();
```

to this
```php
$required_fields = array();
```

**Comment by timgavin** [comment]
`$ php -v` returned 8.2 but for some reason I was actually using 8.1. I'm seeing all the errors now. Thanks for the heads up!
