### ISSUE TITLE
Select Multiple not working in fastform

### ISSUE THREAD

**Issue by McJono** [formr/Formr#165]
Just wondering if anyone has managed to get select_multiple to work within fastform. I'm finding that every time I try to use it while doing fastform it seems to be defaulting to a normal select, without the multiple attribute.
`
'select_multiple' => [
   'name' => 'meals',
   'label' => 'Meals Given This Shift',
   'options' => $mealsgiven
],
`

Am I just doing something wrong or is it not working?

**Comment by timgavin** [comment]
It's a bug; fixing coming soon.

Also, when using `select_multiple()`, you'll want to use brackets in your name to tell PHP it's an array, otherwise PHP will only select one item from the list.

```
'select_multiple' => ['name' => 'meals[]', ...
```
