### ISSUE TITLE
Email error even when empty

### ISSUE THREAD

**Issue by McJono** [formr/Formr#166]
I have a contact form that allows anonymous people to send emails however, when someone doesn't fill out the email address it errors out with the following error:

`Please Correct the Following Error

email must be an email address`

I noticed there is a !empty($value) so I'm a little confused as to why this is happening.

I am using fast form and this is the line for the email input:
'email' => 'email,Email',

**Comment by timgavin** [comment]
My bad. Formr isn't checking if the field is empty, so it's spitting out that error. I'll address this in the next update.

For now it's an easy fix. Go to line 2310 (or there about) and replace the following

```
$rule == 'email' && !filter_var($data['post'], FILTER_VALIDATE_EMAIL)
```

with this

```
$rule == 'email' && !empty($data['post']) &&  !filter_var($data['post'], FILTER_VALIDATE_EMAIL)
```
