### ISSUE TITLE
Form fields are susceptible to XSS

### ISSUE THREAD

**Issue by bfzgaier** [formr/Formr#168]
It is possible to inject html code into the page using the formfield generated by formr.

How to reproduce:
```php
$form = new Formr\Formr();

// make all fields required
$form->required = '*';

// check if the form has been submitted
if ($form->submitted())
{
    // get our form values and assign them to a variable
    $data = $form->validate('Name');

    // show a success message if no errors
    if($form->ok()) {
        $form->success_message = "Thank you";
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<body class="container">
    <?php $form->messages(); ?>
    <?php $form->create_form('Name'); ?>
</body>
</html>
```

Payload: `"><script>alert('XSS');</script>`

After submitting the form with the payload, the malicious JavaScript is injected into the page.

https://github.com/formr/formr/blob/195273e43c42d60d3be4893876d854edf85d2a98/class.formr.php#L3002-L3011

Formr treats every tag attribute the same, but at least the value attribute should be html escaped, as it is controlled by the user.

```php
        foreach ($data as $key => $value) {
            if (!in_array($key, $this->no_keys)) {
                if($key != 'checkbox-inline') {
                    if ($value != '') {
                        if($key == 'value') {
                            $value = htmlspecialchars($value);
                        }
                        $return .= ' ' . $key . '="' . $value . '"';
                    }
                }
            }
        }
```

**Comment by timgavin** [comment]
Just use [validation rules](https://formr.github.io/validation/#validation-rules) on each input and you're all set.

```php
$data = $form->validate('Name(sanitize_string)');
```

returns: `alert('XSS')` (no tags)

**Edit (for clarification)**

Formr really shouldn't be in the business of deciding what input you receive; that's up to each developer. So what you should do is just use validation rules to decide what data you want.

You can also do the following and get the same result

```php
$data = $form->validate('Name');
$name = strip_tags($data['name']);
```

I've also submitted the form using your code (without using validation rules) and did not receive an alert popup, so it appears the page is not being taken over by the script.

I've double-checked your code and it too returns `alert('XSS')` even without validation; so the tags are being stripped.

```php
$data = $form->validate('Name');

echo $data['name']; // returns alert('XSS') without the <script> tags
```

**Comment by bfzgaier** [comment]
Validation rules do not solve the issue. As long as the form is rerendered with the user input, for example on an form error, you have an injection.

Add a second field to the form with an validation. Add the payload to the first field use the second to trigger a validation error. The form is rerenderd and the payload is injected into the page.

Or use an email field and postman, or adjust the input type attribute to work around browser validation.

**Comment by timgavin** [comment]
Ok, I'm seeing it now. Thanks for letting me know, and for your persistence. :)

**Comment by timgavin** [comment]
It's been a while since I've dealt with this so I didn't have a ready answer, but what you should do is just use the `sanitize_html` filter, which will run the input through `filter_var($str,FILTER_SANITIZE_SPECIAL_CHARS)` and remove XSS vulnerability.

```php
$form->required = '*';
$form->sanitize_html = true;
```

Again, the reason for this is so that people can allow HTML input if they want. I should probably reverse this and disable HTML by default, however that would be a breaking change.

I'll think about this.
