### ISSUE TITLE
Setting custom error message for validation

### ISSUE THREAD

**Issue by ghost** [formr/Formr#17]
First, really loving this script! Makes it so much easier. Had one issue though, when doing validation I want to be able to supress any errors that may come up except the custom one I set. For example:

`$form->post('lp','Password|Invalid Login/Password','sanitize_string|alpha_dash|min_length[6]');`

I do not want to tip hackers to any requirements for the password field. No matter what, if there was any validation issues, I want it to show my custom error message of Invalid Login/Password. Now this works if it doesnt meant the requirements, except min_length. If it doesnt meant that, it gives an error message of:

> Password must be at least 6 characters

If I pass it a custom error message, IMO the error above shouldnt show up, only the custom error message I am passing. Is there anyway you can change this or give me the option to suppress the errors from the validation rules and only show my custom error message?

**Comment by ghost** [comment]
Also Im having the same problem with another function, the matches function. If I do this:

```
$form->post('lp1','Password|Enter password field is required','sanitize_string|alpha_num|min_length[6]');
$form->post('lp2','Password|Re-enter password field is required','sanitize_string|alpha_num|min_length[6]|matches[lp1]');
```

If both fields do not match, it gives this error:

> The Password field does not match the lp1 field

I simply want it to use the custom error I provided, Re-enter password field is required. Is that how its suppose to work or am I looking at it incorrectly?

**Comment by timgavin** [comment]
That's what it's like for all of the validation fields. I think I have something that works, but haven't been able to fully test it yet and just don't have time right now. Let me know your email address and I'll send you a copy so you can play with it and let me know if it works for you.

**Comment by ghost** [comment]
> 
> 
> That's what it's like for all of the validation fields. I think I have something that works, but haven't been able to fully test it yet and just don't have time right now. Let me know your email address and I'll send you a copy so you can play with it and let me know if it works for you.

Then I guess I dont understand. This is what I read off the documentation:

> Example: Create a custom error message string
> 
> // adding a pipe (`|`) character after the human readable text will create a custom error string
> $form->post('email','Email|Please enter your email address','valid_email');

[](https://formr.github.io/validation/)

I was assuming if I specify the custom error message string, it will override the built in error message with the custom one I provided.

**Comment by timgavin** [comment]
if you look at the `post()` method, it explains how it works

[https://formr.github.io/methods/#post](https://formr.github.io/methods/#post)

"The optional second parameter contains the human readable text for this field, which will be inserted into the error message. **It can optionally contain a custom error message string that will be shown if the field is required, yet left empty when submitted**."

I have something working that will override that behavior and ONLY show the custom error message.

**Comment by ghost** [comment]
> 
> 
> if you look at the `post()` method, it explains how it works
> 
> https://formr.github.io/methods/#post
> 
> "The optional second parameter contains the human readable text for this field, which will be inserted into the error message. **It can optionally contain a custom error message string that will be shown if the field is required, yet left empty when submitted**."
> 
> I have something working that will override that behavior and ONLY show the custom error message.

Is there a way to message you directly? Dunno about putting my email address here.

**Comment by timgavin** [comment]
This is fine.


The following *should* display your custom validation messages only; hiding Formr’s default messages.

$form->custom_validation_messages = true;

I’ve been sweating over that variable name as well. It’s a little long, however it *is* somewhat descriptive as to what it does.



Thanks,

Tim

**Comment by timgavin** [comment]
tim at timgavin dot name

**Comment by timgavin** [comment]
I sent a file to you a couple days ago and have not heard back. Is it working?

**Comment by ghost** [comment]
Sorry for taking so long. I been busy with another project. I promise to test it tomorrow and get back to you. Again my apologize. You been so good with getting back to me and I havent returned the same.
Robert

    On Friday, July 12, 2019, 3:21:06 PM MST, tim gavin <notifications@github.com> wrote:  
 
 
I sent a file to you a couple days ago and have not heard back. Is it working?

**Comment by ghost** [comment]
Hey, just letting you know I tested it out and it works like a charm. With the old script it gave me the error message:
Password must be at least 6 characters
With the new code it gave me my custom error I assigned to it. Thanks for getting this fixed!
Robert



    On Friday, July 12, 2019, 3:21:06 PM MST, tim gavin <notifications@github.com> wrote:  
 
 
I sent a file to you a couple days ago and have not heard back. Is it working?
