### ISSUE TITLE
Textarea XSS injection

### ISSUE THREAD

**Issue by manuelh78** [formr/Formr#173]
Hi, 

Please, don't use $_POST directly.
If you write <script>Alert(123)</script> in a textarea, you have a security problem.  
You can copy GET/POST vars into an array and remove bad HTML tags ? probably in _construct() 

line 3383 :
```
       # insert the posted value if available
        if (! empty($_POST[$data['name']])) {
            $return .= $_POST[$data['name']];
        } else {
            # insert the default value if available
            if ($this->is_not_empty($data['value'])) {
                $return .= $data['value'];
            }
        }
```

Thanks

**Comment by timgavin** [comment]
Submitting `<script>Alert(123)</script>` in a textarea does not produce a javascript alert, nor enable an XSS injection, even after submitting the form. All it does is put the string back into the textarea.

Build a form, add `<script>Alert(123)</script>` to a textarea named `comments`, and submit it. You will see that echoing the `$comments`  variable produces `Alert 123` without the `<script>` tags, which is safe.

```
$form = new Formr\Formr;

if ($form->submitted()) {
	$comments = $form->post("comments");
	echo $comments;
}

$form->create_form('comments|textarea');
```

**Comment by manuelh78** [comment]
Hi,
Look at the attached image.
Thanks

![screenshot_postvar](https://github.com/formr/formr/assets/42542452/76a72056-8e61-4c34-a1c1-fbdb80e1a959)

**Comment by timgavin** [comment]
It's not important what data is inside the textarea. What's important is what you do with that data _after_ the form is submitted.

`$_POST` contains the submitted, raw form data, and then Formr removes the script tags and leaves "Alert(123)" as the value. The output is safe.

You are free to do additional escaping and sanitization with your form data. However, in this case you don't need to, so I'm failing to grasp what your issue is?

**Comment by timgavin** [comment]
I decided to take another look at this and you're correct; what I was doing was wrong. I've updated the code in a few places to use `htmlspecialchars($value, , ENT_QUOTES, 'UTF-8')` to assist in preventing XSS attacks. Thank you for your assistance and patience.
