### ISSUE TITLE
Validate file input with $form->uploads = false; ?

### ISSUE THREAD

**Issue by coteo** [formr/Formr#175]
Hi Tim,

is it possible to have an input of type file marked as required ($form->required = 'myFileInput';) but with the upload by Formr desactivate ($form->uploads = false;).

I need to check that the field is filled and ideally that it contains a file of type image ($form->upload_accepted_types = 'jpg,jpeg,gif,png';).

Thank you,

Alexandre for Coteo Agency

**Comment by timgavin** [comment]
Sorry, this isn't something I'll be adding to Formr. I'm sure there's a way to do this in PHP, like checking if Formr is submitted, then checking the `$_FILES` array?
