### ISSUE TITLE
Having trouble getting formr up and running....

### ISSUE THREAD

**Issue by danhilliard** [formr/Formr#176]
<?php
require_once 'class.formr.php';
$form = new Formr\Formr('bootstrap');
$form->create_form('Name, Email, Comments|textarea');

Parse error: syntax error, unexpected '|', expecting ';' or '{' in C:\wamp64\www\formr\lib\class.formr.wrappers.php on line 18

**Comment by timgavin** [comment]
I'm going to need to see more of your code as I suspect your problem lies somewhere else.

This works as expected, even when using different wrappers.
```php
$form = new Formr\Formr();

$form->create_form('Name, Email, Comments|textarea');
```
