### ISSUE TITLE
Select-Field does not work with Wordpress

### ISSUE THREAD

**Issue by OlivierZe** [formr/Formr#177]
Hi

I have been looking for something exactly like Formr for a long time and am happy to have found it. Unfortunately, I have a problem with the select field when integrating it into Wordpress. I have tested Formr on a clean PHP application and it works so far.
Now I wanted to integrate it on a Wordpress page. Unfortunately, only the label is created in the form for the select field. I have already deactivated all plugins and activated the default Wordpress theme.

Now I wanted to ask if you know why this is the case and how to fix it.

I hope you can help me

Best regards,
Olivier

![Screenshot_35](https://github.com/formr/formr/assets/43411700/e44731d1-88f3-4ee2-9476-d893487b003c)

**Comment by timgavin** [comment]
Sorry, I'm not familiar enough with Wordpress to offer any actual assistance on this. When I use your code (please don't use a screenshot when asking coding questions) everything works as expected, even with output buffering.

Maybe try StackOverflow?
