### ISSUE TITLE
Validating manually built forms

### ISSUE THREAD

**Issue by AndiLeni** [formr/Formr#178]
Hello,

I want to manually build my form to have more options and because the syntax is clearer than fastform.
However, I am not able to properly validate my form and show error messages and apply valid and invalid css classes to the forms. 
Do I have to do this manually in this case?

This is a small example form I created:

```php
$form = new Formr\Formr('bootstrap', 'hush');

$nachname = $form->text('nachname', 'Nachname');
$vorname = $form->text('vorname', 'Vorname');
$phone = $form->text('phone', 'Rückrufnummer');
$email = $form->email('email', 'E-Mail Adresse');

if (!$form->submitted()) {
    echo $form->messages();

    echo $form->open();

    echo $nachname;
    echo $vorname;
    echo $phone;
    echo $email;
    echo $form->submit_button("Absenden");

    echo $form->close();
} else {

    $nameval = $form->post('nachname', "Bitte Nachname angeben.", "required");
    $vornameval = $form->post('vorname', "Bitte Vornamen angeben.", "required");
    $phoneval = $form->post('phone', "Bitte Telefonnummer angeben.", "required");
    $emailval = $form->post('email', "Bitte E-Mail angeben.", "email");

    if ($form->ok()) {
        echo "Form OK!";
        echo $form->messages();
    } else {
        echo "Form NOT OK!";
        echo $form->messages();

        echo $form->open();

        echo $nachname;
        echo $vorname;
        echo $phone;
        echo $email;
        echo $form->submit_button("Absenden");

        echo $form->close();
    }
}
```

This does not seem to be the correct syntax, as no css classes are applied and no error messages are shown?
Could you point out how to fix this?
I think this would be a nice example for the docs too.

Thanks and kind regards
Andreas

**Comment by AndiLeni** [comment]
I think I was able to find my issue.
My expectation was, that errors are shown above the form by default when I place `$form->messages()` somewhere in my code.
However, it seems like I have to set `$form->inline_errors = true;` to achieve this.
Which is a little counter-intuitive in my opinion, as this option does indeed enable inline-errors but also seems to enable the output of error messages at the top with `messages()`.
So I basically can have both (top and inline) or none of them.

Can you confirm this issue?

Kind regrads

**Comment by timgavin** [comment]
You're over complicating  it, and missing a crucial piece to showing your error messages under each element: the `inline_errors` property.

https://formr.github.io/properties/#inline_errors

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body class="container">
```

```php
 <?php
 include '../vendor/autoload.php';
  $form = new Formr\Formr('bootstrap', 'hush');

  // adding this will show an error message under each field
  $form->inline_errors = true;

  // add this if you want to add the `required` attribute to all form fields
  $form->required = '*';
  
  if ($form->submitted()) {
  	$nameval = $form->post('nachname', "Bitte Nachname angeben.", "required");
  	$vornameval = $form->post('vorname', "Bitte Vornamen angeben.", "required");
  	$phoneval = $form->post('phone', "Bitte Telefonnummer angeben.", "required");
  	$emailval = $form->post('email', "Bitte E-Mail angeben.", "email");
  	
  	if ($form->ok()) {
  		echo "Form OK!";
  	} else {
  		echo "Form NOT OK!";
  	}
  }
  
  // add this if you want to show your error messages in a bootstrap alert
  $form->messages();

  echo $form->open();
  echo $form->text('nachname', 'Nachname');
  echo $form->text('vorname', 'Vorname');
  echo $form->text('phone', 'Rückrufnummer');
  echo $form->email('email', 'E-Mail Adresse');
  echo $form->submit_button("Absenden");
  echo $form->close();
?>
```

```html
</body>
</html>
```

**Comment by timgavin** [comment]
> I think I was able to find my issue. My expectation was, that errors are shown above the form by default when I place `$form->messages()` somewhere in my code. However, it seems like I have to set `$form->inline_errors = true;` to achieve this. Which is a little counter-intuitive in my opinion, as this option does indeed enable inline-errors but also seems to enable the output of error messages at the top with `messages()`. So I basically can have both (top and inline) or none of them.
> 
> Can you confirm this issue?
> 
> Kind regrads

Yes, this is somewhat counter intuitive, and actually confused me when replying because this isn't how it's supposed to be! Formr originally showed the error messages in an alert, and then you'd use `inline_errors` to disable that and display the errors under each field.

I apparently broke something along the way... Apologies for the confusion I caused!

**Comment by AndiLeni** [comment]
Thank your for the reply and for your example code, mine was indeed not minimal. And no worries about the confusion!

If you are going to fix this bug, may I suggest one more idea? 
It could be handy in some cases to either show the error messages
- on the top only
- inline only
- at the top and inline 
- or not at all

Maybe you could change the current behavior to use two properties, one for enabling/disabling inline errors and one for enabling/disabling top errors.

Setting properties like this would make the functionality behave like it currently is to not break existing stuff but also allow finer control for future usecases.
```php
$form->inline_errors = false; //default false, toggles inline errors
$form->top_errors = true; //default true, toggles top errors
````

A usecase where it can be useful to display both error types would be a multistep form which is rendered with javascript. 
The user submits the form and all the errors are shown a the top, which might be the first page of a multi step form. 
Then the user paginates trough the form steps where the invalied fields are visibly marked too for a quick recognition where the errors are.

**Comment by AndiLeni** [comment]
Since you have already closed the issue, do you have an estimate when there will be a fix for this problem?

**Comment by AndiLeni** [comment]
@timgavin I think this issue was introduced in your last commit "updated for PHP 8.1, added Tailwind wrapper, etc" 0044558 in class.formr.php.
You changed the line `if ($this->inline_errors == false)` { to `if ($this->inline_errors) {`.
Reverting this line seems to fix this issue.

**Comment by timgavin** [comment]
Good catch! I don't have an ETA but I'll get to it as soon as I can. Thanks for the assist!

**Comment by timgavin** [comment]
Formr has been updated with your recommendation. Thanks again!
