### ISSUE TITLE
compress image size of upload image

### ISSUE THREAD

**Issue by sanojlawrence** [formr/Formr#18]
am using below code to upload image is there any way to compress image size `

        $form->upload_dir = 'uploads';
        $form->upload_rename = 'hash';
        $form->upload_accepted_mimes = 'image/jpg,image/jpeg,image/gif,image/png';
        if ($form->submit()) {
            $file = $form->post('file');
            $form->printr($file);
        }
        echo $form->messages();
        echo $form->form_open_multipart();
        echo $form->csrf(1800);
        echo $form->input_upload('file[]', 'Photo 1');
        echo $form->input_submit();
        echo $form->form_close();
`

**Comment by timgavin** [comment]
Yes, check out the `$upload_resize` property.

https://formr.github.io/upload-files/#upload_resize

**Comment by sanojlawrence** [comment]
sorry small mistake,

how do i **compress** image size while **uploading** and create thumbnail. With below form

    `$form->upload_dir = 'uploads';
    $form->upload_rename = 'hash';
    $form->upload_accepted_mimes = 'image/jpg,image/jpeg,image/gif,image/png';
    if ($form->submit()) {
        $file = $form->post('file');
        $form->printr($file);
    }
    echo $form->messages();
    echo $form->form_open_multipart();
    echo $form->csrf(1800);
    echo $form->input_upload('file[]', 'Photo 1');
    echo $form->input_submit();
    echo $form->form_close();`

**Comment by timgavin** [comment]
Same answer as last time, check out the `$upload_resize` property. There's a complete example right there in the docs.

**Comment by timgavin** [comment]
There's also a screencast on how to do this on the home page of the Formr docs.
