### ISSUE TITLE
'selected' is ignored if form is entered by post

### ISSUE THREAD

**Issue by nilswald** [formr/Formr#19]
Hi Tim,

if you enter a form by a post from another form, e.g. a login, the 'selected' values are completely ignored:

```
2563 # check the element on initial form load
2564            if (!$_POST) {
```
I think you should rather ask for the specific form element:
```
2564            if (!isset($_POST[$data['name']])) {
```

Nils

**Comment by timgavin** [comment]
Can you give me an example?

I'm not sure what you mean by: "if you enter a form by a post from another form" and that the 'selected' values are ignored.

**Comment by nilswald** [comment]
I am doing an event registration form. First I have to enter an invitation code, which brings me to the actual details form. When generating this form, $_POST is not empty and formr tries to populate the fields from $_POST rather than using the values specified by the 'selected' parameter.

Here's a demo:
![2019-08-03 10 54 18](https://user-images.githubusercontent.com/1010163/62409809-1f5b7c80-b5dd-11e9-9021-14a9ea73ac37.gif)

**Comment by timgavin** [comment]
Understood and have implemented your suggestion. Thanks!
