### ISSUE TITLE
radio with value = 0 ignores 'selected'

### ISSUE THREAD

**Issue by nilswald** [formr/Formr#20]
Hi Tim,

a radio button using `'value' => 0, 'selected' => 0`does not return the `checked` option. Strings '0' also do not work. Checkboxes not tested.

Nils

**Comment by timgavin** [comment]
Using `'value' => 0` should now work.

Using `'selected' => 0` will not work because you're telling Formr `'selected' =>  false`. Instead, use `'selected' => true`.
