### ISSUE TITLE
How do i create bootstrap input group

### ISSUE THREAD

**Issue by sanojlawrence** [formr/Formr#21]
i create input group with below group code in bootstrap is there any way to create input group in formr

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">@</span>
     </div>
      <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
    </div>

**Comment by timgavin** [comment]
Formr creates this automatically. Take a look at the README, all you have to do is tell Formr you want to use Bootstrap when instantiating it.

```
$form = new Formr('bootstrap);
```
