### ISSUE TITLE
radio inline not working due to warning / message

### ISSUE THREAD

**Issue by astrakid** [formr/Formr#22]
hi,
i am trying to get radio buttons displayed inline, but unfortunately i get a warning message after each radio button called "Please enter a value for the radio: <radioname>". If this message is removed all radios are displayed inline.
How can I remove this warning or get it displayed at the end of the radio-group?

`echo $form->input_radio_inline('meal','all');
echo $form->input_radio_inline('meal','vegetarian');
echo $form->input_radio_inline('meal','vegan');
echo $form->input_radio_inline('meal','fruits');
echo $form->input_radio_inline('meal','nothing');
`

regards,
andre

**Comment by astrakid** [comment]
this is what it looks like, also it shoudl be displayed inline:
![image](https://user-images.githubusercontent.com/5278642/64062029-5aec6500-cbe2-11e9-8e8f-40471afb3596.png)

**Comment by astrakid** [comment]
here some more infos:
this is the html code generated:

![image](https://user-images.githubusercontent.com/5278642/64062044-9b4be300-cbe2-11e9-9c2f-2403676551d4.png)

if i remove the <p>-parts with errors it looks correct:

![image](https://user-images.githubusercontent.com/5278642/64062063-d4845300-cbe2-11e9-80f4-0cce44cf61f2.png)

**Comment by timgavin** [comment]
Your radios don't have a default value, which is why you're seeing those error messages. You need to add a value...

```
echo $form->input_radio_inline('meal','all','all');
echo $form->input_radio_inline('meal','vegetarian','vegetarian');
echo $form->input_radio_inline('meal','vegan','vegan');
echo $form->input_radio_inline('meal','fruits','fruits');
echo $form->input_radio_inline('meal','nothing','nothing');
```
