### ISSUE TITLE
Is this lib using some cache?

### ISSUE THREAD

**Issue by vulantro** [formr/Formr#23]
Hello!

I am using this lib and I find a potential bug. I print a form as the documentation expains, but send the data with ajax js. The server processes it and sends back the same form, now filled with the entered data and js overrides the sended form with the filled one got back. The problem, that if I do not refresh the page, but modify something with php between sending the data and saving to the db, the lib gives back the data entered and not the actual one in the db (and modified by php before saving). Everything is working,, db data is ok, the lib is called with exactly the same paramters except value, but no change. If I refresh the page, the right data is shown from the db.
If I echo an input manually with the same parameters (and value), everything is working, actual db content is shown regardless the typed ones.
The $form is opened and closed in the same script, so in theory, it should not exist after saving and a new object is created for reproducing the form with the database data.
Reprinted form is called exatly like the first print, not like this:
`<input type="text" name="fname" value="<?php echo $form->value('fname'); ?>">`

**Comment by timgavin** [comment]
No, Formr does not use a cache. I suspect this has something to do with your JavaScript or PHP settings.
