### ISSUE TITLE
Please put this library on Packagist/Composer

### ISSUE THREAD

**Issue by aoxborrow** [formr/Formr#25]
I would like to use Formr for the Bootstrap 4 form generation, but it's 2019 and I'm not adding unversioned dependencies to my app. Would you accept a pull request to setup the library for Composer? You would need to create the account at Packagist.

**Comment by wairos** [comment]
I would love for this to happen! I sometimes use the fork xlad/formr which is actually on packagist, https://packagist.org/packages/xlad/formr, for convenience, but its not up to date with formr/formr.

**Comment by ldco** [comment]
Same here!
By the way -  the xlad/formr version is outdated, can't install it with composer.

**Comment by timgavin** [comment]
I'm open and willing and now have some time with the quarantine lol. I'm familiar with using Composer but not creating packages, so would be thankful for some assistance/guidance.

I also want to make sure this isn't going to cause any issues for non-developers, such as designers who just want an easy way to process forms. Would be great if they could continue to install via .zip download, and everyone else can use composer.

My big question: Do I need to namespace this? Looking at xlad's implementation... all he did was create a `composer.json` file. If that's all I need to do, then no problem!

I'll also need to get up to speed on versioning and pull requests... all I do is commit lol

**Comment by timgavin** [comment]
Formr can now be installed via Composer.
