### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in class.formr.php on line 1177

### ISSUE THREAD

**Issue by chrilleferna** [formr/Formr#35]
When moving one of my sites from local environment to a staging server I get a warning when uploading a file. The file IS uploaded.  My code is extacly the same. One difference is that the local site runs PHP 7.1.32 and the staging PHP 7.2.

**Comment by chrilleferna** [comment]
Switched to PHP 7.2 on the local environment (MacOS) and now the same warning. So apparently it is related to the version pf PHP

**Comment by chrilleferna** [comment]
The reason is that PHP 7.2 seems to be more picky, and does not like count applied to a string. So I changed the line 1177 from:
`if(count($_FILES[$name]['tmp_name']) > 1) {`
to
`if(is_array($_FILES[$name]['tmp_name']) && count($_FILES[$name]['tmp_name']) > 1) {`

**Comment by timgavin** [comment]
Thank you, I'll apply it.
