### ISSUE TITLE
input_checkbox() creates weird label

### ISSUE THREAD

**Issue by Kukulkano** [formr/Formr#37]
Hi, 

if I create a new checkbox like this
```
// hint: input_checkbox($data, $label = '', $value = '', $id = '', $string = '', $inline = '', $selected = '')
echo $form->input_checkbox("chkReverse", "Reverse-Charge", "1", "chkReverse");`
```
the produced code looks like this:
```
<label for="1">
	<input type="checkbox" name="txtReverse" id="1" value="1"> Reverse-Charge
</label>
```
$data and $id are set to "chkReverse", but the $id is ignored. Also, the label surrounds the <input> tag instead to become closed before.

All other inputs generate code like this (which is okay):
```
<label for="">VAT Amount</label> 
<input type="number" name="txtVAT" id="txtVAT" class="input" style="width: 60px;">
```

I expect the above example to produce code like this:
```
<label for="">Reverse-Charge</label> 
<input type="checkbox" name="txtReverse" id="txtReverse" value="1">
```

**Comment by timgavin** [comment]
When I enter this:

```
echo $form->input_checkbox("chkReverse", "Reverse-Charge", "1", "chkReverse");
```

It produces this, which is what you're expecting.

```
<label for="1">
	<input type="checkbox" name="chkReverse" id="chkReverse" value="1" required> Reverse-Charge
</label>
```

Your samples contradict themselves (chkReverse vs. txtReverse). Are you looking at the correct code in your file?

**Comment by Kukulkano** [comment]
Sorry, seems I was not clear enough but the issue is real. Use this code:
```
$form = new Formr();
echo $form->form_open("","","?p=customer");
echo $form->input_checkbox("chkReverse", "Reverse-Charge", "1");
echo $form->input_text("txtVAT", "VAT Amount");
echo $form->form_close();
```

Producing this output:
```
<form action="?p=customer" method="post" accept-charset="utf-8">

<label for="1">
	<input type="checkbox" name="chkReverse" id="1" value="1"> Reverse-Charge
</label>

<label for="">VAT Amount</label> 
<input type="text" name="txtVAT" class="input" id="txtVAT">

</form>
```
Three problems here:
1. The _checkbox_ _label_ is surrounding and the _text_ _label_ is on top. Inconsistent. Bad for CSS.
2. The _checkbox_ is not using the name as _id_. Instead, it uses the _value_. Bug?
3. The _text_ _label_ does not set the _for_ attribute to the ID. Bug?
