### ISSUE TITLE
Validation of input_tel phone number 

### ISSUE THREAD

**Issue by manuelh78** [formr/Formr#38]
in function _process_post($data)
I add this code :

            # valid tel
            if ($rule == 'tel')
            {
                $post=trim($post);
                $matches=null;
                if ($post!='' && !preg_match("#^[0-9\.\-\s]*$#us", $post, $matches))
                {
                    var_dump($matches);
                    if($this->_suppress_validation_errors($data)) {
                        $this->errors[$name] = $data['string'];
                    } else {
                        $this->errors[$name] = $label . ' must be a valid phone number';
                    }
                }
            }

**Please can you update the github with last corrections (for example : https://github.com/formr/Formr/issues/32 

i lost time with this knwon problem :)**

**Comment by timgavin** [comment]
Is this validating US numbers only?

Edit: I'm testing your code and it's not validating; everything passes.

**Comment by manuelh78** [comment]
It's a not very strict control for France (my users) and may be Belgium, Spain and UK. 
For france : 0x.xx.xx.xx.xx or 0x xx xx xx xx or 0x-xx-xx-xx-xx

https://en.wikipedia.org/wiki/Telephone_numbers_in_France
https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom
https://en.wikipedia.org/wiki/Telephone_numbers_in_Belgium
https://en.wikipedia.org/wiki/Telephone_numbers_in_Spain

**Comment by timgavin** [comment]
I think there needs to be a more generic way to do this; I don't want to install validations just for France and a few other countries.

Perhaps there's a way to add a validation class that extends your proposed `tel` validation, so that we can do `tel[fr]`, or `tel[us]`, etc.? Or maybe even  add the pattern directly, such as `tel["#^[0-9\.\-\s]*$#us"]`, but maybe this might get confusing?

I also want to keep things clean and not get too crazy. I'll have a think on this...

**Comment by manuelh78** [comment]
Hi,

A generic way will :

        $tel = $this->post('tel', '', 'preg[[0-9\.\-\s]*]|min_length[10]');

but a better solution would be to put all strings in 2 files with :

- all defaults errors messages (currently in _process_post())

- all specifics country format

and add a function $this->setLanguage('fr'); //en by default

; for example for phone numbers
$check_tel = ['us'=>'xxx', 'fr'=>'[0-9\.\-\s]*'' ...];

or

$check_tel = ['us'=>function($post) { }, 'fr'=> function($post) { return $post!='' && !preg_match("#^[0-9\.\-\s]*$#us", $post, $matches)) }];

a user clean code will :

$this->setLanguage('fr');
...
$tel = $this->post('tel', '', 'tel');

or

$tel = $this->post('tel', '', 'tel[fr,sp,us]');
