### ISSUE TITLE
Errors don't displayed in inline mode

### ISSUE THREAD

**Issue by manuelh78** [formr/Formr#41]
V1.1
I don't understand why in_array() return false; I changed by  isset(); 
may be a problem with == != === ?

line 311 : 
````
        //if (in_array($key, $this->errors)) {
        if (isset($this->errors[$key])) {
            return true;
        }
````

line 2362: 
````
<div class='xxx'>IS EMPTY</a>; I add .$this->errors[$name].

        # add div if using inline errors
        if ($this->in_errors($name) && $this->inline_errors) {
//            return '<div class="' . $this->inline_errors_class . '"></div>';
            return '<div class="' . $this->inline_errors_class . '">'.$this->errors[$name].'</div>';
        }
````

**Comment by timgavin** [comment]
I'm sorry, I don't really understand what you're trying to say.

**Comment by manuelh78** [comment]
Hi,

Here you use a simple array  : 
````
    public function add_to_errors($str)
    {
        # add a string to the errors array
        array_push($this->errors, $str);
    }
````

but in _process_post() you add errors with a key : 
 ````
 $this->errors[$name] = $data['string'];
````

it'a "mixed" array, it's not a good practice:)

But here : 
````
    public function in_errors($key)
    {
        # checks the errors array for the supplied key

        $key = trim($key, '[]');

        if (in_array($key, $this->errors)) {
            return true;
        }

        return false;
    }
````
the function **in_array()** return always false in my server. I don't know why. But what do you want to test : keys or values ?

maybe you should use array_key_exists() or isset (more faster).

**Comment by manuelh78** [comment]
2nd problem ; here :
````
public function inline($name)
    {
        # add div if using inline errors
        if ($this->in_errors($name) && $this->inline_errors) {
            return '<div class="' . $this->inline_errors_class . '"></div>';
        }
    }
````

you return a empty div  ````<div class='xxx'>NOTHING</div>````

You don't display errors in inline mode. Probably just a icon with css rule.
replace NOTHING by .$this->errors[$name].
I changed by : 
````
return '<div class="' . $this->inline_errors_class . '">'.$this->errors[$name].'</div>';
````

Thanks.

**Comment by timgavin** [comment]
First issue. We're basically just adding strings to the errors array in the `add_to_errors()` function, which creates a key of `0`. When we add an error in `_process_post()` we're adding a key so we know which field to highlight, Regardless, if you `print_r($this->errors)` you get something like the following, which is fine.

```
Array
(
    [0] => error string 1
    [fname] => fname error string
)
```

I'll check out the inline errors issue and fix if required. However, and it's been a while, but I'm pretty sure that was supposed to be a class that you would design yourself, like you said, using an inline image, etc.

Thanks.

**Comment by timgavin** [comment]
Just wanted to add that if you look at line 78 you'll see the following

```
# inline validation CSS class: displays error icon next to form fields
public $inline_errors_class = 'error_inline';
```

So yes, inline errors was meant to have an icon, not text.
