### ISSUE TITLE
Auto re-populate issue with input_text

### ISSUE THREAD

**Issue by titibdotcom** [formr/Formr#46]
Hello, and thank you for you great job!
I have a problem with the method input_text() re-populate value action. I have a very simple form, with only one input and one submit, used for create and modify content. 
Here is a small version of my script which produce the problem. 
When you access it with ?u=1 (update), you can see the text to update... but when you submit, it still shown. Same with adding. 
And the stranger things is after submitted, the value for input_text and input_submit does not follow the same rule... (see the placeholder and submit value).

I don't know if I'm clear but I hope the script is :-)

Thanks again. 

titib

```
<?php
require_once('lib/config.php');

$update = $_GET['u'];
if($update == '1') {
  // get data from database...
  $tag_data = 'content to modify';
}

$form = new Formr('bootstrap');
if($form->submit()){
  $update = '0';
  if($form->post('submit') == 'Modifier') {
    // update in database
  }
  else {
    // add in Database
  }
}

if($update == '1') {
  $form_placeholder = 'Name to modify';
  $form_tag = $tag_data;
  $form_submit = 'Modify';
}
else {
  $form_placeholder = 'Name to add';
  $form_tag = '';
  $form_submit = 'Add';
  $update = '0';
}
echo 'update = '.$update;

echo $form->messages();
echo $form->form_open();
echo $form->input_text('tag','',$form_tag,'tag','placeholder="'.$form_placeholder.'" class="form-control"');
echo $form->input_submit('submit','',$form_submit,'submit','class="btn btn btn-outline-primary"');
echo $form->form_close();
```

**Comment by timgavin** [comment]
When you submit the form you are using the `POST` method, but when you set the `$update` variable you are using the `GET` method. You need to set `$update` with the `POST` method.
