### ISSUE TITLE
validate method undefined?

### ISSUE THREAD

**Issue by chrilleferna** [formr/Formr#48]
I just added the following validation statement:

`$form->validate('firstname, lastname, email, phone, appointment_date');`

which resulted in the following error message in the browser:

`Fatal error: Uncaught Error: Call to undefined method Formr::validate() in ...`

$form is defined and refers to a submitted form, since I pick up post parameters without any problem.

I quickly scanned the Formr source code and didn't see any definition of validate function. Does it still exist?

**Comment by timgavin** [comment]
I just tested and it worked as it should, echoing out the `phone` field to the browser. Are you using an old version of Formr that doesn't have the `validate()` function? Please download the current version and try it again.

```
<?php
require_once 'Formr/class.formr.php';
$form = new Formr('bootstrap');

if($form->submitted()) {    
    $data = $form->validate('firstname, lastname, email, phone, appointment_date');
    echo $data['phone'];
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Formr</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <?php
            echo $form->messages();
            echo $form->create_form('firstname, lastname, email, phone, appointment_date');
        ?>
    </div>
</body>
</html>
```

**Comment by chrilleferna** [comment]
Yep, that was the problem. I dowloaded the latest version and validate is now defined.
Thanks for your quick help!

**Comment by timgavin** [comment]
Great!
