### ISSUE TITLE
Composer does not install v1.1.2

### ISSUE THREAD

**Issue by wairos** [formr/Formr#49]
Cannot install v1.1.2 with Composer only v1.1

I think the version number needs to be omitted in composer.json. Right now the version is set at 1.1 in composer.json.

Found this on Packagist.org:
The easiest way to manage versioning is to just omit the version field from the composer.json file. The version numbers will then be parsed from the tag and branch names.

**Comment by timgavin** [comment]
Thank you; it's been updated.
