### ISSUE TITLE
allow_html MUST come last

### ISSUE THREAD

**Issue by chrilleferna** [formr/Formr#5]
First Tim, let me tell you how happy I am to have found Formr. I just started using it for Wordpress and it works exactly they way I wanted! Great job, and the tutorial videos are perfect!

Now to a minor issue: I noticed that when using the rule 'allow_html', this rule must come last if there are several rules (such as also checking the max_length). If not the html tags will be stripped. You could either fix this or just spell it out in the documentation.

**Comment by timgavin** [comment]
Thanks for the kind words, and good catch! Fixed with https://github.com/formr/Formr/commit/6ed5491dcfffc1b96e07ad026c5764eabc1c2f0d
