### ISSUE TITLE
Composer versioning is not resolved yet.

### ISSUE THREAD

**Issue by wairos** [formr/Formr#50]
Composer is still not able to install v1.1.2 it's stuck on 1.1

I've forked formr and tested this locally and got it to work by creating a new tag, v1.1.3, that includes the composer.json file currently on the master branch.

You could also remove the existing tags and then add them back with fixed composer.json files that have the version field omitted, but that seems like more trouble than it's worth. I would just make the new tag and be done with it. Hope this helps!

**Comment by timgavin** [comment]
Tagged a new version: 1.1.3. Thanks for you help on this, I have no idea what I'm doing lol
