### ISSUE TITLE
error_message text does not accept the wrapper div given in messages() function.

### ISSUE THREAD

**Issue by rudolphp** [formr/Formr#52]
- if this is set: `$form->error_message('Invalid Username')`
- then function `$form->messages('<div class="alert alert_error"><div class="alert_icon icon-alert"></div><div class="alert_wrapper">','</div></div>')` does not wrap the error message nicely, like it does for validation messages.

**Comment by rudolphp** [comment]
I tried with second param ($flash) as true. It still same issue.

**Comment by timgavin** [comment]
Why are you adding all of the HTML and Bootstrap classes to the `messages()` function? It does that for you automatically.

Perhaps I'm misunderstanding what you're sayin; can you give me an example?

**Comment by timgavin** [comment]
Closing this as I believe you're using the function improperly. Just do like the following...

```
$form->error_message('Invalid Username');
$form->messages();
```
