### ISSUE TITLE
Example: Create an input with an associative array

### ISSUE THREAD

**Issue by Guustaaf** [formr/Formr#55]
The example does not include the "label" variable that appears to be required.
Otherwise a very helpful library.

**Comment by timgavin** [comment]
To which example are you referring? Please give more context.

**Comment by Guustaaf** [comment]
Methods -> Inputs -> input_text() -> Example: Create an input with an associative array.

Also, is there a reference anywhere showing all the variables that can be passed?

**Comment by timgavin** [comment]
Seems there is a bug in the wrapper class. I've fixed it but want to run some more tests before pushing. For a workaround just set `'label' => null` in the array.

You can find the variable docs for `input_text()` here: https://formr.github.io/methods/#input_text

**Comment by Guustaaf** [comment]
I have two more things that you can perhaps include in your update :)
1. Please change "Taiwan, Province of China" to "Taiwan"
Taiwan is an independent country and not a part of China. (I live in Taiwan)
2. I am creating select inputs by passing an associative array and it seems to work well, except for setting an option as selected. I am trying to do it by including a variable with the key "selected" but that does not seem to work.
Thanks!

**Comment by Guustaaf** [comment]
I also have a feature request, perhaps for later. Maybe you can add a method called input() that creates an input type based on a variable that you pass to it in an array. (As in Create an input with an associative array.) I like creating all the inputs from arrays because then I can store the whole form definition as a 2D associative array that can then also be used by backend code.

**Comment by timgavin** [comment]
I've fixed the wrapper issue and updated 1 (Taiwan) in the dropdown class.

Please create a new issue for 2 (creating select inputs by passing an associative array) and provide a code sample so I better understand what's going on.

I'll add the `input()` method in another commit.

**Comment by Guustaaf** [comment]
Awesome Tim!
I will create the new issue.
