### ISSUE TITLE
Creating a <select> form element by passing an associative array works too

### ISSUE THREAD

**Issue by Guustaaf** [formr/Formr#56]
$select_element = [
        "name" => "style_id",
        "id" => "form_element_1",
        "label" => "Style ID",
        "options" => [
            1 => "Abstract Expressionism",
            2 => "American Realism",
            3 => "Baroque",
            4 => "Cubism"
        ],
        "selected" => 2,
        "value" => ''
    ];

echo $form->input_select( $select_element );

**Comment by Guustaaf** [comment]
Something undocumented that works is not really an issue so I'm closing it.

**Comment by timgavin** [comment]
I've added an example to the docs. Thanks!

**Comment by Guustaaf** [comment]
I saw it. Thanks Tim. Good stuff.
