### ISSUE TITLE
Text Input 5th parameter for text string gets messy when included in error

### ISSUE THREAD

**Issue by ec1warc1** [formr/Formr#57]
If I have a string in the 5th parameter of text input, and I do something wrong in the form, it screws up the styling. 
```
<div class="row">
<div class="col-md">

<?php
if($ip_wait_secs > 0) {
    $form_disabled='disabled';
} else {
    $form_disabled='autofocus';
}

// Commenting out my workaround here:
//if(($form->in_errors('desired_username'))&&(!$ip_wait_secs > 0)){
    $form_disabled='class="form-control is-invalid" autofocus';
}

echo $form->input_text('desired_username',$fs[0],'','',$form_disabled);

if($ip_wait_secs  > 0){
    $form_disabled='disabled';
} else {
    $form_disabled=null;
}
?>
</div>
<div class="col-md">
```
![2020-04-27_9-45-46](https://user-images.githubusercontent.com/23389201/80386296-d2a38a00-886c-11ea-9fea-5b06fd3eeefb.jpg)

![2020-04-27_9-46-10](https://user-images.githubusercontent.com/23389201/80386327-ddf6b580-886c-11ea-8d21-35f106829788.jpg)

My workaround is to include the form-control and is-invalid classes if there is an invalid string input by the user.

Many thanks for an outstanding product and best wishes for continued success!

**Comment by timgavin** [comment]
You don't need to add `form-control` in your class as it's already added if you're using Bootstrap, so you can just do the following and it'll work.

```
$form_disabled = 'class="is-invalid" autofocus';
```

Second, if you just print out an `input_text()` field using your string, you'll see it works as it should.
```
echo $form->input_text('foo','Foo','','','class="is-invalid" autofocus');
```

So the problem you're experiencing is elsewhere in your code and unlikely caused by Formr. Maybe check and see what the value of `$fs[0]` is? Perhaps that's breaking something?

**Comment by ec1warc1** [comment]
I have simplified the code down to next to nothing, and still get this problem. It works slightly better when I comment out ```$form->required='*';``` for example (only red text does not appear). Try it yourself! It is broken!
```
<?php
include_once rtrim($_SERVER['DOCUMENT_ROOT'], DIRECTORY_SEPARATOR) . '/forms/Formr/class.formr.php';
$all_error_messages = array(null);

?>
<!DOCTYPE html><html lang=""><head><title>whatever</title>
<script src="https://kit.fontawesome.com/f0361b12ce.js" crossorigin="anonymous"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</head><body>
    <div class="container-fluid">
        <div class="row justify-content-center" style="margin-top:0.4rem;">
            <div class="col-xs-10 col-sm-10 col-md-8 col-lg-7 col-xl-6">
<?php
$form = new Formr('bootstrap');
$form->required='*';
if($form->submit()){$form->add_to_errors('desired_username');}
$var='autofocus';
//$var=null;
echo $form->form_open();
echo $form->input_text('desired_username','Desired Username Description','','',$var);
echo $form->input_submit('','','','','');
?></div></div></div></body></html>

```

**Comment by ec1warc1** [comment]
![2020-04-27_14-01-49](https://user-images.githubusercontent.com/23389201/80410255-e6141c80-888f-11ea-973c-a14bd9a60791.jpg)
![2020-04-27_14-02-03](https://user-images.githubusercontent.com/23389201/80410266-ead8d080-888f-11ea-8752-c44240bbaf98.jpg)

**Comment by timgavin** [comment]
Ok, I think I see what's going on here. It appears that the `form-control` class is not being added to the input when manually adding an item to the errors array.

It might take me a while to figure out a fix, so in the mean time do what you were doing before and manually add the `.form-control` class to the input.

Using the code you provided, I did this to the field and it's now formatted correctly when submitted.

```
echo $form->input_text('desired_username', 'Desired Username Description', '', '', 'class="form-control" autofocus');
```
