### ISSUE TITLE
Using medoo class inside my.dropdowns

### ISSUE THREAD

**Issue by titibdotcom** [formr/Formr#59]
Hello, 

I'm trying to access my database inside my.dropdowns. For this I use [Medoo class ](http://medoo.in). I have an external config file like this:
```
require_once('Medoo.php');
use Medoo\Medoo;
$database = new Medoo([
	'database_type' => 'mysql',
	'database_name' => 'database',
	'server' => 'localhost',
	'username' => 'root',
	'password' => 'root',
	'charset' => 'utf8',
	'prefix' => 'db_'
]);
```

I tried something like this and it work but it's really messy (especially the fact I need to include the config file multiple times)... Do you have any idea how to do in a better way?

```
class MyDropdowns {
    public static function all_tags()
    {
        require('../lib/config.php');
        $content =  $database->select('content', ['id','title'],['ORDER'=>['title'=>'ASC']]);
        foreach($content as $t) {
            $return[$t['id']] = $t['title'];
        }
        return $return;
    }
}
```

Thanks

titib

**Comment by timgavin** [comment]
Off the top of my head, no. Not sure there's anything else you can do?

However, I'll look into passing an array to the functions within MyDropdowns to make this easier...

**Comment by timgavin** [comment]
You can now [pass an array](https://github.com/formr/Formr/commit/090462daf1fc9b4b72200eb50a90a51daa06c421) as the 9th parameter of the `input_select` methods

```
$data = [
    'foo',
    'bar',
    'baz'
];

echo $form->input_select('foos','','','','','','','my_function',$data);
```

```
class MyDropdowns {
    public static function my_function($data)
    {
        foreach($data as $key => $value) {
            $return[$key] = $value;
        }

        return $return;
    }
}
```

**Comment by titibdotcom** [comment]
Thanks :-)
