### ISSUE TITLE
Options check

### ISSUE THREAD

**Issue by gilcot** [formr/Formr#6]
Hello,

I get `key`/`text` pairs from a remote database I don't own (so I cannot just change the keys...) with `key`s being integers. 

Now, here's my issue, with the following 3 pairs:
```php
// labels are changed, but the keys are the same
$pairs = arrayr(
    0 => "foo",
    1 => "bar",
    3 => "baz",
);
// then let's create a simple drop down menu with it
$form->input_select('pairs', '', '', "choose", $pairs);
```
...the result was strange as "foo" was automatically defaulted instead of "choose"

Later, I've been told they can be combined and change my code this way
```php
foreach ($pairs as $v => $l) {
    $form->input_select('pairs[]', $l, $v, "pairs_$v");
}
```
Now I have that error/red message: "Please enter a value for the checkbox: pairs[]" 

For me, it's a bug because zero is a value and it shouldn't behave as if an true empty string or undefined/unset variable is passed.

**Comment by timgavin** [comment]
I believe this was resolved in https://github.com/formr/Formr/commit/8b3b86cb18feabbc287011d321e66cdc1ee47666

Also, the options must be the 8th parameter of the `input_select()` function;

```
$pairs = array(
    0 => "foo",
    1 => "bar",
    3 => "baz",
);

echo $form->input_select('pairs', '', '', "choose", '','', '', $pairs);
```

**Comment by gilcot** [comment]
Great (at first look, 8b3b86c should fix it) I'll give a try very soon. Thanks.
