### ISSUE TITLE
Extends rules ?

### ISSUE THREAD

**Issue by titibdotcom** [formr/Formr#60]
Hello,

I have some specifics need for the post validation rules (phone num, date, etc.). It could be great to have a specific file in my_class folder to add some personal rule. 

What do you think about that? 

Thanks again for your great job! 

titib

**Comment by timgavin** [comment]
I'll think about it but can't promise anything, especially since it's pretty easy to do your own validations inline.

For instance, if you wanted to validate a phone number...

```
if($form->submitted()) {
    $phone = $form->post('phone');
    if(! preg_match("/^[0-9]{3}-[0-9]{4}-[0-9]{4}$/", $phone)) {
        $form->add_to_errors('phone');
    }
}
```
