### ISSUE TITLE
Auto typing for various types is probably wrong

### ISSUE THREAD

**Issue by PYL666** [formr/Formr#61]
https://github.com/formr/Formr/blob/090462daf1fc9b4b72200eb50a90a51daa06c421/class.formr.php#L842

From my understanding, this should read:
```php
(mb_substr($key, 0, 4) == 'file')
```

**Comment by PYL666** [comment]
Further reading suggests a full review of the function is needed: I seems that lots of indices are wrong.
(Or I did not understand the code.) 😄

**Comment by timgavin** [comment]
I'm hoping it was just a mistake on my part - perhaps by copy/pasting and not updating the numbers - rather than doing it on purpose and now not being able to remember the reason why!

**Comment by PYL666** [comment]
creating some predicate function like this might help:
```php
function starts_with($key, $str) { return mb_substr($key, 0, strlen($str)) == $str; }
```
Because, strictly speaking, it is a case of implicit double representation of the same information, that is, the string and its length.

**Comment by PYL666** [comment]
BTW: I love you micro-framework: it **really** helps.

Thank you! 😸

**Comment by timgavin** [comment]
Looks good. I've added that function and will play around with it to test. thank you!
