### ISSUE TITLE
issue with mutiple selected checkboxes not prepopulated fields.

### ISSUE THREAD

**Issue by prasnala** [formr/Formr#63]
Thanks for your awesome work. It same my lots of time. Currently creating wordpress plugin for my website lawyeronphone.com. This is marketplace for lawyers and clients. I find if we select multiple checkboxes it is not prepopuplated. 

I work on that and resolve also. But I am not sure how to use this github. I hope my solution will be find interesting to you. 
![Screenshot_2020_05_18_17_05_44](https://user-images.githubusercontent.com/1866897/82209063-472c8e80-992a-11ea-9786-001904de0291.jpg)

**Comment by prasnala** [comment]
I hope that will help you to improve this plugin... all the best keep doing best work.

**Comment by timgavin** [comment]
Please copy/paste your HTML for the checkboxes.
