### ISSUE TITLE
Switch bootstrap 3 of 4 

### ISSUE THREAD

**Issue by mikecastrodemaria** [formr/Formr#64]
It look you can use bootstrap 4.X by default, but seem possible to use bootstrap 3.X.
$form = new Formr('bootstrap');
Is activating boostrap 4

Is it possible to use : 
$form = new Formr('bootstrap3');
Or
$form = new Formr('bootstrap4');

Thanks

**Comment by timgavin** [comment]
Yes, that's exactly how it works.
