### ISSUE TITLE
Bugs/Feature Requests

### ISSUE THREAD

**Issue by Coyote6** [formr/Formr#65]
Hi I am testing out your composer project and really like the simplicity of your calls.  Not hard to understand and doesn't take a lot of time to implement or have to compile a ton of needed libraries.  A few things I noticed (sorry for grouping these all together but didn't want to send in a lot of different tickets:

1. The class wasn't wrapped in a namespace.  A simple `namespace Formr;` at the top of the page should do the trick.  May check into doing the same with any other classes you are using, just in case someone else's project uses the same class name.
2. If the action is left to the default action, query parameters in the url get dropped.  Simple to fix by setting the action, but can create an issue if someone doesn't set it and submits.  I am integrating it with a Wordpress plugin to handle my admin settings forms, and if the action is not explicitly set, the page submits to _/wp-admin/admin.php_ instead of _/wp-admin/admin.php?page=sample_plugin&tab=settings_ which leads to a white screen of death. (Guessing you may have dropped the parameters in case someone uses the get method.)
3. The location for setting a custom wrapper is another issue.  I am not 100% sure how this is working yet, but currently it says to use the location inside of the my_classes directory, which falls inside of the vendor folder when using composer.  If I was to update that file to my settings, it would work, but if I ever was to run composer update, it would overwrite my customizations.  Maybe if we could add a setting like you did with the _htmlpurifier_, to tell the path of the custom wrappers instead, it would work better and allow users to make custom wrappers without having to worry about them being overwritten on update.
4. Move session variables into a single 'formr' array to prevent clashing of session variables from other systems.  Example, the $_SESSION['token'] could easily be used by the CMS or other template system, where as $_SESSION['formr']['token'] would be far less likely. (You may turn the csrf token on by default as well, if it is not already.)
5. Add a better way to set a form errors externally.  Maybe add a set_error ($field_name, $str) call. Your _add_to_errors()_ method doesn't allow you to specify a field name. You can use `$form->errors[$name] = 'Error Message.';` but it would seem cleaner as a method.

Other than that, nice work.  Will let you know if I notice anything else as I am messing around with it.

**Comment by timgavin** [comment]
Good ideas.

Have already added `$_SESSION['formr']`to every `$_SESSION` in the class and will push that in the next update.

I don't know why I added the files in `my_files` as I knew that would be breaking, and the documentation even gives instructions on how to set that up! My guess is that I accidentally pushed my local setup instead of deleting it before the initial commit and then just left it. I'll think about how to address that, because I don't want it to be a breaking change. which it probably won't be because I'm only removing files...

**Comment by timgavin** [comment]
Now that I think about it, adding `$_SESSION['formr']` will potentially be a breaking change for some... I've removed it for now.

**Comment by timgavin** [comment]
You can now add custom messages to the `add_to_errors()` method like so. This will be available in the next release.

```
$form->add_to_errors('fname|Please enter your first name');
```

**Comment by timgavin** [comment]
There's now a method for adding a custom message to the `add_to_errors()` method and will be included in the next release.

```
$form->add_to_errors('name|Please enter your name');
```

```
if(!$form->in_errors('email') && $email == 'email@website.com') {
    $form->add_to_errors('email|Email can not be email@website.com');
}
```
