### ISSUE TITLE
Quote and repopulate

### ISSUE THREAD

**Issue by titibdotcom** [formr/Formr#68]
Hello,

I have a issue when I use ", < or ' in a input_text. 
The re-populate function doesn't work. 

For exemple, if I write 
`test "Hello World"`
only
`test `
is repopulate. The content is well passed by POST but the repopulation seems to have a problem. 

Do you have any idea how to fix it ? 

Thanks in advance,

I.

**Comment by timgavin** [comment]
That's because special characters get stripped to prevent injection attacks. Try using the `allow_html` validation rule to bypass the filter.

Use with caution!

https://formr.github.io/validation/#validation-rules

**Comment by titibdotcom** [comment]
I have the exact same problem with allow_html. 

I just want these characters (<>") are passed by htmlentites($var,ENT_QUOTES). And it does (in my db). The only problem is with the repopulation function. 

Everything else works great.
