### ISSUE TITLE
Quote problem with allow_html

### ISSUE THREAD

**Issue by titibdotcom** [formr/Formr#69]
Hello,

The followed issue is not solved in fact : https://github.com/formr/Formr/issues/68

=>

I have the exact same problem with allow_html. 

I just want these characters (<>") are passed by htmlentites($var,ENT_QUOTES). And it does (in my db). The only problem is with the repopulation function. 

Everything else works great.

_Originally posted by @titibdotcom in https://github.com/formr/Formr/issues/68#issuecomment-683582612_

**Comment by timgavin** [comment]
Ok, let's try this. Go to line 2424...

**Change this**

```
$data['value'] = $this->_clean_value($_POST[$data['name']]);
```

**To this**

```
$data['value'] = $this->_clean_value($_POST[$data['name']], 'allow_html');
```

and let me know if it's working as you'd expect.

---

**Full Context**

This is inside the `_create_input()` method

```
# run the data through the clean_value function and clean it
if ($this->session_values && $this->session) {
    $data['value'] = $_SESSION[$this->session][$data['name']];
} else {
    $data['value'] = $this->_clean_value($_POST[$data['name']], 'allow_html');
}
```

**Comment by timgavin** [comment]
I have also added a `$form->sanitize_html` property so that you can pass the `$_POST` values through PHP's `FILTER_SANITIZE_SPECIAL_CHARS` filter, which will turn `<` into `&#60;` and so on...

**Comment by titibdotcom** [comment]
Hello & Thank you for your answer. Your first proposition doesn't work. 
And I'm sorry, but I don't get what your propose about $form->sanitize_html.

**Comment by timgavin** [comment]
Apologies, the change is actually on line 2410, not 2424. I just installed a fresh copy of Formr using Composer and it's working as intended: HTML tags are appearing in the text input as expected.

On line 2410 of a fresh install, changing this

```
$data['value'] = $this->_clean_value($_POST[$data['name']]);
```

to this

```
$data['value'] = $this->_clean_value($_POST[$data['name']], 'allow_html');
```

will allow HTML in the input fields. If it's not working for you, then please describe what you did and how it's not working. Saying "it's not working" doesn't help me fix it.

**Comment by titibdotcom** [comment]
Hello. Sorry to answer only now. I hadn't time to this before. 

I try with a fresh install and it still doesn't work…

**Comment by timgavin** [comment]
Please show your code.
