### ISSUE TITLE
request: more attributes

### ISSUE THREAD

**Issue by gilcot** [formr/Formr#7]
Hello,

I can see there are many "Form Validation Rules". :+1: 
I think it may be nice if some of them are also included as HTML attribute (if not in extra arguments string) 

Formr | HTML5 
-------|---------
matches |  pattern
min_length |  
max_length | maxlength
exact_length | 
greater_than | max 
less_than | min
alpha |  pattern*
alpha_numeric |  pattern*
alpha_dash |  pattern*
numeric | pattern*
integer |  pattern*
decimal |  pattern*
valid_email |  pattern*
valid_ip |  pattern*

Regards.

**Comment by timgavin** [comment]
I don't understand what you're asking; please provide some examples. Thanks.

**Comment by timgavin** [comment]
Ok, I think I understand what you mean, but you'd have to tell me why you want them because it seems adding validation rules as `data` attributes would clutter the api. I don't see any reason for them.

**Comment by gilcot** [comment]
Hello,

No, no, I  don't ask for change of the API: validation rules should remain validation rules :) 

But, I'm a bit frustrated when using HTML5 it can't produce something like 
```html
<input type="number" name="quantity" min="1" max="5">
```

**Comment by timgavin** [comment]
Sure you can

```
echo $form->input_number('quantity', 'Quantity', '', '', 'min="1 max="5"');
```

Produces

```
<input type="number" name="quantity" id="quantity" class="form-control" min="1 max="5">
```
