### ISSUE TITLE
Repopulate multicheckbox

### ISSUE THREAD

**Issue by titibdotcom** [formr/Formr#70]
Hello,

Is there's a way to auto-repopulate the multicheckboxes. It does work perfectly with something like this:
` echo $form->input_checkbox('name','label1','val1','id1','unchecked');`

But not with something like this:
` echo $form->input_checkbox('name[]','label1','val1','id1','unchecked');`

Thanks

**Comment by timgavin** [comment]
Multiple checkboxes will repopulate; just tested it myself with the following code and it's working fine. Perhaps you're using an older version of Formr when this was broken?

```
echo $form->form_open();
echo $form->input_checkbox('name[]', 'label1', 'val1', 'id1', 'unchecked');
echo $form->input_checkbox('name[]', 'label2', 'val2', 'id2', 'unchecked');
echo $form->input_submit();
echo $form->form_close();
```
