### ISSUE TITLE
form-control class not added to fields

### ISSUE THREAD

**Issue by sri20198** [formr/Formr#73]
Hi,

I have used the basic example and find that the _form-control_ class is not added to the fields in the HTML output.

![Screenshot 2020-09-08 at 5 15 45 PM](https://user-images.githubusercontent.com/3481060/92472337-f43b5780-f1f6-11ea-8cb3-f2f921de66bb.png)

**Comment by timgavin** [comment]
If you have the most recent version, go to line 601 (in the `_fix_classes()` method)

And change this...

```
if ((strpos($element, 'class=') === false) && (isset($data['string']) && strpos($data['string'], 'class=') === false))
```

to this (All you're doing is changing the `&&` to `||`)...

```
if ((strpos($element, 'class=') === false) || (isset($data['string']) && strpos($data['string'], 'class=') === false))
```

...and let me know if that fixed it for you.
