### ISSUE TITLE
Can I use formr with the Twig template engine?

### ISSUE THREAD

**Issue by ghost** [formr/Formr#74]
Formr is a really nice framework which saves a lot of time. 

I'm new to PHP and searched the internet, but I found no hints on combining Formr with the Twig template engine. Is that generally possible at all?

Any help would be welcome. Thanks in advance.

**Comment by timgavin** [comment]
I don't see why not. I'm not familiar with Twig, but I just took a quick look at their docs and it looks like you should be able to use Formr with no problems. Just install Twig with composer, then install Formr with composer, then build your Formr forms as you normally would.
