### ISSUE TITLE
Set checkbox checked

### ISSUE THREAD

**Issue by mcazzador** [formr/Formr#75]
I I'm matteo, i'm using formr, i notice in the new versions some trouble settings checkbox checked.

When i use version 1.1 always is ok.

When i switch to 1.2 i don't see any chechkbox checked.

I set correctly $checked = 'checked'

$form->input_checkbox($label_variabile.'[]',$label,"$key",$id_domanda."_$k","",'',$checked);

Thanks

**Comment by timgavin** [comment]
My guess is that your problem is somewhere else because I just did the following and it's working as expected.

Code
```php
$checked = 'checked';
echo $form->input_checkbox('name[]', 'Name', 'key', 'IDkey', "", '', $checked);
```

Result
```html
<label for="IDkey">
    <input checked type="checkbox" name="name[]" id="IDkey" value="key"> Name
</label>
```

Adding another works as expected too

```php
$checked = 'checked';
echo $form->input_checkbox('name[]', 'Name 1', 'key1', 'IDkey1', "", '', $checked);
echo $form->input_checkbox('name[]', 'Name 2', 'key2', 'IDkey2', "", '', $checked);
```

```html
<label for="IDkey1">
    <input checked type="checkbox" name="name[]" id="IDkey1" value="key1"> Name 1
</label>

<label for="IDkey2">
    <input checked type="checkbox" name="name[]" id="IDkey2" value="key2"> Name 2
</label>
```

**Comment by mcazzador** [comment]
Thank's i will re-check my code with new version.

**Comment by mcazzador** [comment]
Hi, only for information i find this difference, old code line (line 2464)

$return.=' checked="checked"';

New code

return .= ' checked';

I use  bootstrap4

Il 18/10/2020 20:20, tim gavin ha scritto:
> Questa è la prima volta che ricevi un'email da questo mittente. 
> Assicurati che sia qualcuno di cui ti fidi.
>
> Closed #75 
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fformr%2FFormr%2Fissues%2F75&e=d9b44b61&h=b20bf2d4&f=y&p=y>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fformr%2FFormr%2Fissues%2F75%23event-3890504943&e=d9b44b61&h=a15f2dcb&f=y&p=y>, 
> or unsubscribe 
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPMZE75JN3ETIY7AZM67MRTSLMWXFANCNFSM4SVGKVLQ&e=d9b44b61&h=5ac2b806&f=y&p=y>.Web 
> Bug from 
> https://github.com/notifications/beacon/APMZE77LVOQ3W2AIVRSUCK3SLMWXFA5CNFSM4SVGKVL2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGO47SGJ3Y.gif
>
>
> -- 
> Messaggio analizzato da Libraesva ESG.
> Segnala come spam. 
> <http://mailgateway-3.netlite.it/cgi-bin/learn-msg.cgi?id=F15DD61965.A6C27>
> Mettilo in blacklist. 
> <http://mailgateway-3.netlite.it/cgi-bin/learn-msg.cgi?blacklist=1&id=F15DD61965.A6C27> 


-- 

Rispetta l'ambiente: se non ti è necessario,  non stampare questa mail.


Le informazioni contenute in questa e-mail e nei files eventualmente
allegati sono destinate unicamente ai destinatari della stessa
e sono da considerarsi strettamente riservate.
E' proibito copiare, salvare, utilizzare,  inoltrare a terzi e diffondere
il contenuto della presente senza il preventivo consenso, ai sensi
dell'articolo 616 c.p. e della Legge n. 196/2003.
Se avete ricevuto questo messaggio per errore siete pregati di comunicarlo
immediatamente all'indirizzo mittente, nonché di cancellarne il contenuto
senza procedere ad ulteriore o differente trattamento.


******************************************
Ing. Matteo Cazzador
NetLite snc di Cazzador Gagliardi
Corso Vittorio Emanuele II, 188 37069
Villafranca di Verona VR
Tel 0454856656
Fax 0454856655
Email: matteo@netlite.it
Web: http://www.netlite.it
******************************************
