### ISSUE TITLE
textarea css class generation does not work 

### ISSUE THREAD

**Issue by LPTT** [formr/Formr#76]
if I add a css class to my textarea 

```$formr->input_textarea('carDetails','',$carDetails, '','class="formfieldWide"');```

formr generates:

```<textarea name="carDetails" id="carDetails" class="input" class="formfieldWide"></textarea>```

which gets to 

```<textarea name="carDetails" id="carDetails" class="input"></textarea>```

in the browser.

If I change lines 3314 and 3317 in class.formr.php so that I first run _attributes and then _fix_classes, it works.

**Comment by timgavin** [comment]
That makes sense to run them in that order. I'll include that in the next push, thanks.
