### ISSUE TITLE
upload_accepted_mimes / upload_accepted_types does not seem to accept formats other than images

### ISSUE THREAD

**Issue by powertashton** [formr/Formr#77]
Hiya,
I'm trying to create a form submission where users can upload word documents and/or PDFs as part of the form, however I keep the error "Oops! The file was not uploaded because it is an unsupported mime type." or "Oops! The file was not uploaded because it is in an unsupported file type."  irregardless of what I have the accepted mimes or types set to. Is it just straight up not possible to upload other file types using formr or is there a specific way I have to go about this?

**Comment by powertashton** [comment]
Doh, it appears I was including the "." in the file extension when it came to file types... got it working now.

**Comment by timgavin** [comment]
I've updated the code to strip periods from extensions, so this shouldn't happen again. Will be available in the next update. Thanks!
