### ISSUE TITLE
Select with integers

### ISSUE THREAD

**Issue by jvldrm** [formr/Formr#78]
Hello

I've been using your project for my website and it's been very useful for me.

I want to address an issue that has come up in my use of this class: When there is a list with numbers for a select and I want one of the items to be selected by default, 
--Now, it works perfectly if the item is a string--but if it is a number, it will not give the desired solution.

Here's a demo code illustrating the problem

```php
$form = new Formr('bootstrap');

$options = array( '1'=>'1', '2'=>'2', '3'=>'3', '4'=>'4', '5'=>'5', '6'=>'6', '7'=>'7', '8'=>'8', '9'=>'9', '10'=>'10'); 

echo $form->input_select('option_selected', 'Select a number','','','','', '9',$options);

// will now let 9 be selected item

echo $form->input_submit();
echo $form->form_close();
```

```php
$form = new Formr('bootstrap');

$options = array( '1', '2', '3', '4', '5', '6', '7', '8', '9str', '10'); 
echo $form->input_select('option_selected', 'Select a number','','','','', '9str',$options);

// it will make it selected

echo $form->input_submit();
echo $form->form_close();
```

(one work around to this was that I inserted a string at the end of each integer item, and before I send it to the database, I removed it, that's how I'm doing it on my project.)

Now, I went through your code and found the line that detects when an item will be selected

it's line 3690 (of current code)

```
elseif (!isset($_POST[$data['name']]) && $data['selected'] === $key || (is_array($data['selected']) && in_array($key, $data['selected']))) {
```

if you change the `===` to `==` this will take the number as a selected item and will make the first portion of the demo code work.

If this change is applied will this affect other behavior of the program? or what is the reason you selected `===`, why do you want it to be exactly the same datatype?

Or is there another way of using your class to get the desired result?

open to learn and help.
JV

**Comment by timgavin** [comment]
I'll update this in the next push.
