### ISSUE TITLE
no captcha supported?

### ISSUE THREAD

**Issue by Elijha** [formr/Formr#79]
This looks like a great project and I'll follow it along as it grows with interest.. but right now without a simple recaptcha option to include and validate I'm not sure its really 'web' ready.

**Comment by timgavin** [comment]
There are plenty of forms which don't require a captcha, however, I'll consider adding this if I can find the time.

**Comment by timgavin** [comment]
reCAPTCHA v3 is now supported. https://formr.github.io/blog/recaptcha
