### ISSUE TITLE
It doesn't displays values when $value='0'. Same problem with $id, and $label

### ISSUE THREAD

**Issue by a-bentofreire** [formr/Formr#8]
The following code, it won't display the value

```php
$value = '0';
$form->input_text('foo', '', $value, 'foo');
```

The same happens to the other attributes like $label, $id.
Having a $label='0' is rare but $value='0' is common, and I also had problems $id='0' that gives an error that an id is required.

I checked the formr code, and the problem is due of checks:
* `if(empty($var))`
* `if(!empty($var))`
* `if($var)`

unfortunately, in php empty('0') === true, making these forms of checking for empty useless in this case.  
a simple solution, is to rename all:  
* `empty(` with `empty_(`  
* `if\((!?)(\$\w+)\)` with `if($1empty_($2))`

and write a `empty_` function that handles the '0' case.  
I did that myself, unfortunately, I can't disclose due copyrights issues.

**Comment by timgavin** [comment]
Thank you.

Resolved in https://github.com/formr/Formr/commit/8b3b86cb18feabbc287011d321e66cdc1ee47666
