### ISSUE TITLE
Resizing transparent PNG image adds black background

### ISSUE THREAD

**Issue by alexfurr** [formr/Formr#82]
PNGs with transparent backgrounds get black added when doing the resize function.
Looks like this is a solution:

`imagefilledrectangle($tmp_image, 0, 0, $new_width, $new_height, imagecolorallocate($tmp_image, 255, 255, 255));`

before the 
`imagecopyresized`

**Comment by timgavin** [comment]
Thank you, however this is producing an image with a white background instead of transparent.
