### ISSUE TITLE
Refreshing page / creating conditional loop

### ISSUE THREAD

**Issue by Amalia0303** [formr/Formr#84]
Hi there,

I'm having the following issue: If participants refresh/reload a page during the survey in their browser, it would be very helpful to create a page where participants are asked whether they want to want to start the survey from the beginning. If they click on "yes", it would be great if they land on the first page. If they click on "no", it would be great if they could stay on the current page (Background info: In the survey each page shows one item). Right now, I only see the possibility of either creating a loop or removing the loop. In both cases however, formr always jumps to the first item.

Thanks a lot for your help! 
Best

**Comment by timgavin** [comment]
This is beyond the scope of Formr. However, you could accomplish some of this using Formr's `$_SESSION` support.

https://formr.github.io/properties/#session
