### ISSUE TITLE
Formr shouldn't automatically output HTML code

### ISSUE THREAD

**Issue by patriciogb** [formr/Formr#87]
Hi,

I have been happily using your class before even there was a composer installer for it, I love this project and I thank you for that, that's why I created a user in github (I work with gitlab only). Now, back to business. I had to update a project to php8 so I decided to upgrade Formr too, so I used the composer installer and I thought I'd be done with it. 
Unfortunately, I see now that now Formr automatically echos the generated HTML code, which is really not optimal if you use the class together with a template package such as smarty. For example, the method "input_submit" used to return the created button. Now you just simply "echo" it to screen. This is really a nasty bug. Believe me, I totally get why you must have thought this was an improvement. If you use the class in a simple website with spaghetti code (HTML + PHP mixed), this is a no brainer. But as I said, if you want to generate the form first and then use it in a template, then this is not so good. 
A configuration switch would be a good compromise, per default you can set the output to "echo" and if the developer so requieres it, we could pass a parameter in the constructor telling the class that we want the form returned to us. 

For the time being, I opted to extend your class and overwrite all the necessary methods to get the result I want.#

Cheers and keep up the good work!

Patricio

**Comment by timgavin** [comment]
This is a good idea and I apologize for your inconvenience; I didn't even think of template systems! I'll update it.

**Comment by patriciogb** [comment]
Awesome! Thanks for your feedback, looking forward to it and hope you have a nice weekend! 💪🏼

**Comment by timgavin** [comment]
In v. 1.2.5 just add 'hush' when instantiating a form and Formr will no longer echo element and messages

```php
$form = new Formr\Formr('', 'hush');

echo $form->messages();

echo $form->open();
echo $form->text('name', 'Name');
echo $form->submit_button();
echo $form->close();
```

**Comment by patriciogb** [comment]
Awesome! Already updated the code and it works like a charm (obviously). Thanks a lot for your effort! 👏🏼👏🏼👏🏼
