### ISSUE TITLE
Notice: Undefined property: Wrapper::$echo

### ISSUE THREAD

**Issue by sleepless-ninja** [formr/Formr#89]
Small issue...

`Notice: Undefined property: Wrapper::$echo in ../vendor/formr/formr/class.formr.php on line 239`

I'm on PHP 7.4 and this notice comes up. `$echo` needs to be defined outside of the constructor from the looks of it.

Thanks.

**Comment by LPTT** [comment]
handling of $echo is not consistent either:

- Class Formr does not define $echo
- $echo is initialized with true in the constructor
- $echo in line239 is checked against === 'hush'

**Comment by timgavin** [comment]
@sleepless-ninja When do you see this error? I can't recreate it.

**Comment by sleepless-ninja** [comment]
@timgavin it happens when creating a field. ie: `$create->text(..)`.

FYI, as I am using it within WordPress I decoupled it from it's API and still get the same issue.

WordPress has a feature/constant called WP_DEBUG and it elevates error reporting levels. From the horses mouth:

`
...setting WP_DEBUG to true also raises the error reporting level to E_ALL and activates warnings when deprecated functions or files are used; otherwise, WordPress sets the error reporting level to E_ALL ^ E_NOTICE ^ E_USER_NOTICE.`

Of course, the notice goes away once WP_DEBUG is set to false but that's besides the point, as it's still PHP's error reporting.

Maybe you're unable to replicate it because your error reporting doesn't include notices?

**Comment by timgavin** [comment]
@sleepless-ninja Thanks! I should have error reporting on all the time when testing this, rookie mistake. 😒

I added the following code to line 136 and the error goes away. It'll be in the next push.

```
# we can turn off automatic echoing of elements in the constructor
public $echo;
```
