### ISSUE TITLE
Upload_resize bug

### ISSUE THREAD

**Issue by erikdemarco** [formr/Formr#9]
turn on php error reporting 

try this script here:
=> http://formr.github.io/upload-files/#a-complete-example

you will get Warning: imagejpeg(/www/formr/uploads/thumbnails//tn_20M3N2Qr1MRs0zmwkl7Yq4Q9hjZR818W.jpg): failed to open stream: No such file or directory in C:\wamp64\www\httpformr\class.formr.php on line 1368

see this double trailing slashes => '/www/formr/uploads/thumbnails//'?

Why there is double trailing slashes?

**Comment by timgavin** [comment]
Just remove the trailing slash after `thumbnails`

Change this
```
$form->upload_resize = array(
    'thumbnail' => '100,100,tn_,/www/formr/uploads/thumbnails/,90'
);
```

To this
```
$form->upload_resize = array(
    'thumbnail' => '100,100,tn_,/www/formr/uploads/thumbnails,90'
);
```

**Comment by sanojlawrence** [comment]
even after changing to this

`$form->upload_dir = 'uploads';
$form->upload_rename = 'hash';
$form->upload_accepted_mimes = 'images';
$resize = array(
	'thumbnail'	=> '100,100,tn_,/thumb,90',
);
$form->upload_resize = $resize;`

i get following error

`Warning: imagejpeg(/thumb/tn_CY3KXHmZy07389T8x0Rbjk5dGn2yzqLp.jpg): failed to open stream: No such file or directory in C:\Users\Amin\Documents\NetBeansProjects\TEST\form\class.formr.php on line 1407`

**Comment by timgavin** [comment]
Try removing the slash before `thumb` and check your permissions on the uploads directory.

Change this

```
$resize = array( 'thumbnail'	=> '100,100,tn_,/thumb,90', );
```

To this

```
$resize = array('thumbnail'	=> '100,100,tn_,thumb,90');
```

**Comment by timgavin** [comment]
Put the full path to the thumb directory, not just `/thumb`

This is the example given in the docs:

```
$form->upload_resize = array('thumbnail' => '100,100,tn_,/htdocs/uploads/tn/');
```
