### ISSUE TITLE
concatentation of validation rules influences return value

### ISSUE THREAD

**Issue by LPTT** [formr/Formr#93]
example:
input: 0533/123456789

validation: min[6]|max[30]|strip_numeric
result: 0533123456789

validation: strip_numeric|min[6]|max[30]
result: 0533/123456789

It seems that in lines 2073 (# process validation rules) and following
$return is not reused but overwritten by every rule

**Comment by timgavin** [comment]
Good catch. Hmmmmm... 🤔

**Comment by timgavin** [comment]
It's fixed, just doing lots of testing as I had to rewrite the methods quite a bit. Will have it in the next push.
