### ISSUE TITLE
Email automatically validated, even it is not required

### ISSUE THREAD

**Issue by jfax** [formr/Formr#95]
Hi again, 

I tried a lot in the last days to build my forms, great framework, but one issue: 
"If a label contains the word email, Formr will automatically assign the valid_email validation rule."

I have a email-field, but it is not required. The auto-validation throws an error, so I cannot submit. In this case I had to rename label to "e-mail"

**Comment by timgavin** [comment]
How are you using it? Can you give me an example of your code?

**Comment by jfax** [comment]
I till try, I define three fields, an loop the output in the left and the right col. But only the left one should be mandatory
```<?php
$fields = ['Name','Country','Email'];
$form->required = '_Name,_Email';

foreach ($fields as $field) {
  if ($field === "Email") {
    $form->email('_'.sanitize_file_name($field), $field, '', '_'.sanitize_file_name($field));
  } else {
    $form->text('_'.sanitize_file_name($field), $field, '', '_'.sanitize_file_name($field));
  }
}

foreach ($fields as $field) {
  if ($field === "Email") {
    $form->email('_Teilnehmer_'.sanitize_file_name($field), $field, '', '_Teilnehmer_'.sanitize_file_name($field));
  } else {
    $form->text('_Teilnehmer_'.sanitize_file_name($field), $field, '', '_Teilnehmer_'.sanitize_file_name($field));
  }
}

$form->submit_button($ft['send'][$lang]);
?>
```

When I submit form, no error appears, but no email is sending. When I print keys in 
https://github.com/formr/Formr/blob/master/class.formr.php#L4594
`echo "<br>key: " . $key;`

it prints my fields and triggers second email-address in
```key: _Name
key: _Country
key: _Email
key: _Teilnehmer_Name
key: _Teilnehmer_Country
key: _Teilnehmer_Email
```
-> Please enter a valid email address
But I defined only this as mandatory: "_Email", not "_Teilnehmer_Email"

My workaround was te rename email to e-mail

**Comment by timgavin** [comment]
Formr is checking all fields, even if the value is empty... whoops! I'll add the fix in the next push. For now you can apply a simple patch which should fix it for you.

In the `send_email()` method, replace the following line (around 4591)

```
if ($key != 'submit' && $key != 'button') {
```

with this

```
if ($key != 'submit' && $key != 'button' && !empty($value)) {
```

### !Edit

Probably better to put it here instead

```
if (!empty($value) && (strpos(strtolower($key), 'email') !== false) && !filter_var($value, FILTER_VALIDATE_EMAIL)) {
```

**Comment by jfax** [comment]
looks good, thanks, I will close
