### ISSUE TITLE
Csfr - Uncaught TypeError: hash_equals(): Argument #1 ($known_string) 

### ISSUE THREAD

**Issue by xkpx64** [formr/Formr#98]
Thanks for that huge update, i try then csfr and works , but then i decide to put lower number $form->csrf(2); // in seconds
and test again 
![Capture](https://user-images.githubusercontent.com/5773378/112442562-a3371f00-8d54-11eb-9b13-715863d461cc.PNG)

**Comment by timgavin** [comment]
You didn't change CSRF to 2 seconds, you changed it to 2 *milliseconds*, which of course will not work.

To suppress that error, go to line 360 and change the following

```
if (hash_equals($_SESSION['formr']['token'], strval($parts[0]))) {
```

to this

```
if (hash_equals((string)$_SESSION['formr']['token'], strval($parts[0]))) {
```

Edit. I misspoke about the seconds, I just woke up lol. You were right; it's 2 seconds, which is still not enough time for someone to fill out a form :)

**Comment by xkpx64** [comment]
Yea i know about that time is not enough but i just wannted to be sure, there are no errors thrown somewhere.
With your code there is no more error , but i see the token mishmatch two times (kinda strange).
![Capture](https://user-images.githubusercontent.com/5773378/112481137-616f9e00-8d7f-11eb-9a2e-b34caea3e357.PNG)

**Comment by timgavin** [comment]
This will stop it from showing twice, but I'm not seeing WHY it's showing twice. The `if` and the `else` are BOTH being executed... so weird. 

```
if($_SESSION['formr']['token']) {
    $this->_error_message('Token mismatch. Please refresh the page.');
}
```

**Comment by xkpx64** [comment]
Thanks i did like that line 373 , and shows  only once.

```
else {
	if($_SESSION['formr']['token']) {
        $this->_error_message('Token mismatch. Please refresh the page.');
        # reset the token
         $_SESSION['formr']['token'] = null;
	}
 }
```

Before adding the fix , i try to add more fields to the form , and i suspected more mismmatches apper.
Maybe somewhere in loops something breaks. 
But when you use only one field is showing only once miscmatch.

```$form->form_open();
$form->csrf(2); // in seconds 
$form->input_text('onefield','OKey');
//$form->input_password('twofield','twotokens');
//$form->input_password('threefield','threetokens');
$form->input_submit();
$form->form_close(); ```

**Comment by xkpx64** [comment]
**Second Issue is honeypot didn't show as intended** - i should say i use bootstrap
`<input type=text name=your_email_address_here value= style=display:none>`

I use $form->honeypot = 'your_email_address_here'; -- nothing shows
also tried different with 
`echo $form->honeypot = 'your_email_address_here';` which output pic bellow
![Capture](https://user-images.githubusercontent.com/5773378/112653814-77509200-8e57-11eb-9805-e3d3b65f7464.PNG)

Edit: when i change in class
    public $honeypot = null ---> true; 
    the field shows but that is not okey i think


**Third problem of mine is htmlpurifier**
 $form->html_purifier = 'formr/HTMLPurifier.standalone.php'; 
![Capture](https://user-images.githubusercontent.com/5773378/112681488-7c253e00-8e77-11eb-8398-6f490edccf24.PNG)

**Other thing is When disable** `$form->charset = 'UTF-8';`
Error jumps to 878 line in class.formr ( it seems in formr.config must be exacly `$form->charset = 'utf-8'; `not `$form->charset = 'UTF-8';` like i did it, but this is the same (who knows) )

**Comment by timgavin** [comment]
Honeypot is created in the `open()` method; I just tested it and it works.

```php
$form->honeypot = 'eyore';
$form->charset = 'UTF-8';
$form->open('myForm','myFormID','index.php','POST');
```

```html
<form action="index.php" name="myForm" id="myFormID" method="POST" accept-charset="UTF-8">
<input type="text" name="eyore" style="display:none">
```

I'm not having any issues with the other items you mentioned, other than it looks like maybe you've installed HTML Purifier incorrectly? The error says the config file can't be found.

Please don't stack multiple items into one issue, it's really hard to keep track of everything.

Edit: I see what you're doing wrong with `honeypot`; don't echo it, it's a parameter, or in other words a preference. You don't echo those, they're settings. You should look over the docs, because I see you're echoing a lot of things you don't actually have to echo.

**Comment by xkpx64** [comment]
Sorry about the stacking and sorry about honeypot where to place it. 
Now its before  `$form-open ` and it's working perfect

I made video to show you what's happening, didn't class.formr makes automaticly that htmlpurifier_config ?

https://user-images.githubusercontent.com/5773378/112712305-621b4800-8ed7-11eb-9590-63095549eba1.mp4

Also i'am not sure how honeypot is working, but is it suppose to block robots when they type in the honeypot-field.
I try to test and i'am not getting anything ( or maybe i test wrong )

https://user-images.githubusercontent.com/5773378/112713123-2d5dbf80-8edc-11eb-9922-899d9268325a.mp4

**Comment by timgavin** [comment]
For honeypot to work you need to check `$_POST`. The following examples will do a honeypot check if `my_field` has a value. You can add a value to `my_field` in Chrome dev tools, then submit the form and you'll see the form die.

```
$form->honeypot = 'my_field';

if($form->submitted()) {
    $name = $form->post('name');
}

if($form->submitted()) {
    $name = $form->validate('Name');
}

if($form->submitted()) {
    $name = $form->fastpost('login');
}
```

I'm not sure what's wrong with HTML Purifier. I'm testing it and receiving the same errors, and I've followed the documentation to a T. Will keep digging.
