### ISSUE TITLE
No placeholder?

### ISSUE THREAD

**Issue by EggzyGallahad** [formr/Formr#99]
I looked through the documentation but could not find how to give placeholder to generated html input items. The method doesn't take placeholder as an argument.

Please advise.

**Comment by timgavin** [comment]
A placeholder is a string, which can be added in the 5th (string) parameter of any method that accepts 5 parameters, which most do..

```php
$form->text('name', '', '', '', 'placeholder="Your name"');
```

Will produce

```html
<input type="text" name="name" id="name" value="" placeholder="Your name">
```

You can add classes, javascript, and more in this parameter...

```php
$form->text('name', '', '', '', 'placeholder="Name" class="my-class" onclick="foo()" autocomplete="off"');
```
